### ISSUE TITLE
Release Service Bus Track 2 Library Preview 2 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#10276]
This is a parent issue tracking the work planned for Service Bus to release the second preview in May following the [C# .Net Azure SDK guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html) 

Code complete date: May 1st, 2020

- [x] UX Studies 
- [x] Implement Transaction support
- [x] Implement add/remove/get rules features with support for filters and actions
- [x] Bring back the send() overload that takes multiple messages
- [x] Review Track 1 feature requests to understand concerns, comments & discussions to see how it affects the design for the current work
- [ ] Review the feature request to support different AMQP data types in messages

**Comment by ramya-rao-a** [comment]
Closing this epic as the second preview (7.0.0-preview.2) of the Azure.Messaging.ServiceBus package is now released.

Rest of the work is being tracked for Preview 3 in #11839 11724
