### ISSUE TITLE
Event Hubs Client Library for .NET - May Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#10313]
For general summary and goals, please see: [Release Event Hubs Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Design and planning for the receiver link redirect feature
- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Live Tests: Consumer/Receiver Stability and Implementation ([#11074](https://github.com/Azure/azure-sdk-for-net/issues/11074))
- [x] Implement the `Smart Send` Feature ([#11075](https://github.com/Azure/azure-sdk-for-net/issues/11075))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] IoT Hub Connection String Translation Sample ([#11072](https://github.com/Azure/azure-sdk-for-net/issues/11072))
- [x] README link to identity setup script is incorrect  ([#11300](https://github.com/Azure/azure-sdk-for-net/issues/11300))
- [x] Reference documentation ([#9302](https://github.com/Azure/azure-sdk-for-net/issues/9302))
- [x] Changelog ([#9302](https://github.com/Azure/azure-sdk-for-net/issues/9302))
- [x] Samples ([#9303](https://github.com/Azure/azure-sdk-for-net/issues/9303))
- [x] Sustained Scenario Stress Runs ([#11087](https://github.com/Azure/azure-sdk-for-net/issues/11087))
