### ISSUE TITLE
Event Hubs Client Library for .NET - June Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11071]
For general summary and goals, please see: [Release Event Hubs Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone
- [x] Design for allowing the `EventData` body to be created and retrieved as a string ([#11753](https://github.com/Azure/azure-sdk-for-net/issues/11753))
- [x] Design and plan for the receiver link redirect feature ([#10588](https://github.com/Azure/azure-sdk-for-net/issues/10588))
- [x] Design Proposal for Custom Endpoint Address Support ([#11907](https://github.com/Azure/azure-sdk-for-net/issues/11907))
- [x] Design Event Processor load balancing strategy improvements ([#11769](https://github.com/Azure/azure-sdk-for-net/issues/11769))

# Implementation

- [x] Fix test hang for `EventProcessorTests.MainProcessingLoop.BackgroundProcessingStopsProcessingAllPartitionsWhenShutdown` ([#11731](https://github.com/Azure/azure-sdk-for-net/issues/11731))
- [x] Flaky test: ReadEventsFromPartitionAsyncThrowsIfConsumerClosedBeforeRead ([#11870](https://github.com/Azure/azure-sdk-for-net/issues/11870))
- [x] Update IotHub Quickstart sample to use latest Event Hubs SDK ([#11894](https://github.com/Azure/azure-sdk-for-net/issues/11894))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Update the migration guide to document that processor checkpoints from legacy versions are not applied ([#11374](https://github.com/Azure/azure-sdk-for-net/issues/11374))
- [x] Reference documentation ([#11069](https://github.com/Azure/azure-sdk-for-net/issues/11069))
- [x] Samples ([#11070](https://github.com/Azure/azure-sdk-for-net/issues/11070))
