### ISSUE TITLE
Arch board guideline enforcement

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#11123]
We need tooling to detect/enforce the following:
- [ ] API changes (breaks, additions, and modifications)
  - These should automatically open ApiView reviews and notify architects and others of the need to review
- [ ] Track 2 libraries only use "blessed" dependencies
- [ ] Naming conventions (package and API names if detailed in language guidelines)

These will need to be done for each language.
