### ISSUE TITLE
Release Service Bus Track 2 Library Preview 3 for .NET

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11724]
This is a parent issue tracking the work planned for Service Bus to release the third preview in June following the [C# .Net Azure SDK guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html)

Code complete date: June 5th, 2020

- [x] CRUD & list operations using connection string 
- [ ] Design for supporting various AMQP data types for message body 
- [x] Design and implement message body as string
- [x] Tracing support
- [ ] Finalize API changes

**Comment by SeanFeldman** [comment]
@JoshLove-msft according to the list in the issue description, API changes should be finalized in preview 3. Yet I haven't seen an issue about pipelines, which I suspect would have an impact on the API. I've raised an issue about it [here](https://github.com/Azure/azure-sdk-for-net/issues/11986).

**Comment by SeanFeldman** [comment]
Given that " Design for supporting various AMQP data types for message body" and "Finalize API changes", are those tracked separately or elsewhere? Thank you.

**Comment by JoshLove-msft** [comment]
Yep, outstanding items have been moved to new Epic - https://github.com/Azure/azure-sdk-for-net/issues/12384

**Comment by SeanFeldman** [comment]
Now it's crystal clear 😃
Merci!
