### ISSUE TITLE
Event Hubs Client Library for .NET - July Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11743]
For general summary and goals, please see:  [Release Event Hubs Track 2 Updates (#1393)](https://github.com/Azure/azure-sdk/issues/1393).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [ ] Create issues and perform resource planning for the next milestone

# Investigation and Analysis

- [x] Increasing memory usage by EventProcessorClient when no new messages ([#11399](https://github.com/Azure/azure-sdk-for-net/issues/11399))

# Implementation

- [x] Implement Event Processor load balancing strategy improvements ([#11768](https://github.com/Azure/azure-sdk-for-net/issues/11768))
- [x] Restructure `EventHubConsumerClient.ReadEventsFromPartitionAsync` ([#11765](https://github.com/Azure/azure-sdk-for-net/issues/11765))
- [x] [BUG] System.InvalidOperationException at Azure.Messaging.EventHubs.EventProcessorClient+<OnInitializingPartitionAsync>d__60.MoveNext ([#12466](https://github.com/Azure/azure-sdk-for-net/issues/12466))
- [x] [FlakyTest] WithTimeoutPropagatesAnExceptionThatCompletesBeforeTimeout ([#12874](https://github.com/Azure/azure-sdk-for-net/issues/12874))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#11746](https://github.com/Azure/azure-sdk-for-net/issues/11746))
- [x] Samples ([#11744](https://github.com/Azure/azure-sdk-for-net/issues/11744))
