### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 5 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#11948]
This tracks the work to release the Azure Cognitive Search Track2 Preview 5 Library for .NET

### API Review
- [ ] Final architecture board review

### Features

- [ ] Document Operations
  - [ ] Design and implement batching operation for document operations  (#11161)
  - [ ] From previous release (#10600, #8719)
- [ ] Replace generate.ps1 with pointer to fixed swagger files (#10873)
- [ ] Azure.Search: Remove ForwardsClientCalls on generated operations (#10611)

### Testing
- [ ] Write more `SearchIndexClient` and `SearchIndexerClient` tests (coverage for less-common CRUD operations
- [ ] Additional end-to-end tests (#12518)
- [ ] Additional indexer tests (#12519)
- [ ] Fix Track 1 tests (#10602)
- [ ] SearchResources do not clean up indexers or data source connections (#12457)

### Docs
- [ ] Readme unification (#12517)
- [ ] Write lots of samples for docs and XML doc comments
- [ ] Consistent Ref Docs Best Practices (https://github.com/azure/azure-sdk-for-net/issues/10612)

### Release
- [ ] Update README to to remove `--version <version>` command line parameter.
