### ISSUE TITLE
Release Service Bus Track 2 Library Preview 4 for .NET

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#12384]
This is a parent issue tracking the work planned for Service Bus to release the fourth preview in July following the C# .Net Azure SDK guidelines

Code complete date: July 3rd, 2020

🏃 Design and implementation for supporting various AMQP data types for message body
- [x] Settle on serialization plan
- [x] Add batch scheduling
- [x] Implement plugin support
- [x] Finalize API changes
- [ ] Stress tests

**Comment by SeanFeldman** [comment]
> * Implement plugins

@JoshLove-msft, it probably should de "Implement support for plugins" or "Implement incoming and outgoing plugins pipeline". That comes before plugins are created, right? 🙂

**Comment by JoshLove-msft** [comment]
> > * Implement plugins
> 
> @JoshLove-msft, it probably should de "Implement support for plugins" or "Implement incoming and outgoing plugins pipeline". That comes before plugins are created, right? 🙂

Updated!
