### ISSUE TITLE
[Design] Address Feedback from JS/Java User Studies

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12477]
- [ ] In unsupervised recognize sample, show how to search for a certain field name in the dict => https://github.com/Azure/azure-sdk-for-net/issues/12960
- [x] Add to documentation description about what SAS Url is – link to service docs about training (we might already do this) => https://github.com/Azure/azure-sdk-for-net/pull/13078
- [x] Add readme code snippet pointers for statements in key concepts. => https://github.com/Azure/azure-sdk-for-net/pull/13078
- [x] For Copy, hard to find resource id and region. Add docstrings to clarify this more. 
_Add in the documentation how/where to get the region for Copy and the list of available regions_ => https://github.com/Azure/azure-sdk-for-net/pull/13078
- [x] Consider adding a mix of fromUrl and stream overload code snippets in the main readme.
- [ ] `text` vs `text_content` – _clarify ref docs_  => part of #13036 
- [ ] Make sure sync and async links are clearly represented in samples list  => https://github.com/Azure/azure-sdk-for-net/issues/11668
- [x] strongly typed receipt sample => https://github.com/Azure/azure-sdk-for-net/issues/12653

To follow up:
- [ ] Should consider having a `getRow()` or similar. Not natural to have a `getCells()` and diving into the cell information to find the row it belongs to. Also, it could use a better data structure here. [constant pain point to get to the field] - _Follow up (Mariana/Anne) Table indexer issue - https://github.com/Azure/azure-sdk-for-net/issues/9975_
- [ ] 2/5 users attempted and were hopeful that they could pass in the local File URL for the `fromUrl` and that should have worked. Circling back to if we should consider adding an overload that takes in a file input.  - _(Waiting to know Johan's thoughts, Issue - https://github.com/Azure/azure-sdk-for-java/issues/12402#issue-643410189)_ 
- [ ] Add documentation to clarify `LabelText` and `ValueText` -
_Deferred discussion to Architecture board. Consider if renaming fields to `labelData` or `labelTextInformation` should help ?_ => issue #13036

**Comment by maririos** [comment]
Description updated with outcomes for UX studies

**Comment by maririos** [comment]
Issues assigned to every comment. We will keep addressing each one, so closing this uber one
