### ISSUE TITLE
Event Hubs Client Library for .NET - August Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#12548]
For general summary and goals, please see: [Release Event Hubs Track 2 Updates (#1393)](https://github.com/Azure/azure-sdk/issues/1393).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone
- [x] Design Proposal for Idempotent Producer ([#13188](https://github.com/Azure/azure-sdk-for-net/issues/13188))

# Implementation

- [x] EventProcessorClient throws NullReferenceException when using IoT Hub connectionstring([#13131](https://github.com/Azure/azure-sdk-for-net/issues/13131))
- [x] Load Balancer: Detect and Handle Reclaiming Ownership on Restart ([#13191](https://github.com/Azure/azure-sdk-for-net/issues/13191))
- [x] Investigate/Remove Unused Dependencies ([#13190](https://github.com/Azure/azure-sdk-for-net/issues/13190))
- [x] Event Hubs: AAD Auth failure when testing against other clouds ([#12964](https://github.com/Azure/azure-sdk-for-net/issues/12964))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#12549](https://github.com/Azure/azure-sdk-for-net/issues/12549))
- [x] Samples ([#12551](https://github.com/Azure/azure-sdk-for-net/issues/12551))
