### ISSUE TITLE
August Release of Key Vault for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#13015]
# Features

- [ ] Support for 7.1 service version.
- [ ] Add "import" to `KeyOperation`.
- [ ] Add `RevorableDays` to certificate, key, and secret properties.

# Bugs

- [ ] Retrieving multiple secrets asynchronously from Key Vault using SecretClient fails with 401 (#12938)
