### ISSUE TITLE
Track 2 Speech Library Work Tracking Issue 

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#13122]
This issue tracks work identified to get Speech APIs to Track 2 state

Many issues are tracked in API View:
https://apiview.dev/Assemblies/Review/f0c346649b824c449b0fabec867d6993

Additional high-level, cross-cutting  issues/questions:

#### More Urgent/Ambiguous
- [ ] What "Clients" types should this library have? [VoiceProfileClient](https://apiview.dev/Assemblies/Review/f0c346649b824c449b0fabec867d6993#Microsoft.CognitiveServices.Speech.VoiceProfileClient) should not use "Client" suffix
- [ ] What's the auth story and specifically AAD support?
- [ ] Some APIs call REST services and should follow the regular Azure SDK guidelines.
- [ ] We cannot have "surprising" types be disposable. Should we copy data instead?
- [ ] Do we need to refactor some types into a shared library (between Speech, Communications, and possibly other Cognitive)?

#### Less Urgent/Straightforward
- [ ] The library needs to support mocking
- [ ] Generic names need to be removed, e.g. [Connection](https://apiview.dev/Assemblies/Review/f0c346649b824c449b0fabec867d6993#Microsoft.CognitiveServices.Speech.Connection), User, Recognizer, DisposableBase
- [ ] What namespace should we use?
- [ ] Support distributed tracing, logging, telemetry
- [ ] Add cancellation tokens to all APIs that do I/O
- [ ] We should not have pubternal APIs, i.e. namespaces called "Internal".

**Comment by annelo-msft** [comment]
Some additional high-level issues/questions:
- [ ] Track 2 clients are immutable - should Speech clients be as well?
- [ ] Clients lack composability - e.g. TranslationRecognizer adds translation and synthesis functionality directly into a recognizer.  Is this the right pattern for Cognitive in general?
- [ ] Methods are async ... should there be sync methods as well?
- [ ] Factory patterns are used in place of constructors - we avoid this in Track 2.

**Comment by jsquire** [comment]
@pallavit :  Do you know if this is still an active workstream or if we can close out this issue?

**Comment by pallavit** [comment]
No active stream here, closing as not planned.
