### ISSUE TITLE
Event Hubs Client Library for .NET - September Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#13184]
For general summary and goals, please see: [Release Event Hubs Track 2 Updates (#1393)](https://github.com/Azure/azure-sdk/issues/1393).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next 

# Implementation

- [x] Idempotent Publishing Support: Client Infrastructure ([#13941](https://github.com/Azure/azure-sdk-for-net/issues/13941))
- [x] Shared Access Signature Connection String Support ([#14711](https://github.com/Azure/azure-sdk-for-net/issues/14711))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Stress and Stability Testing ([#14000](https://github.com/Azure/azure-sdk-for-net/issues/14000))
- [x] Reference documentation ([#13185](https://github.com/Azure/azure-sdk-for-net/issues/13185))
- [x] Samples ([#13186](https://github.com/Azure/azure-sdk-for-net/issues/13186))
