### ISSUE TITLE
Event Hubs Client Library for .NET - October Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#13937]
For general summary and goals, please see: [Release Event Hubs Track 2 Updates (#1393)](https://github.com/Azure/azure-sdk/issues/1393).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Idempotent Publishing Support: Service Integration ([#14710](https://github.com/Azure/azure-sdk-for-net/issues/14710))
- [x] Integrate PrefetchSizeInBytes Option  ([#15009](https://github.com/Azure/azure-sdk-for-net/issues/15009))
- [x] All Tests fail while authrityhost from environment doesn't end with "/" ([#15009](https://github.com/Azure/azure-sdk-for-net/issues/15009))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#13938](https://github.com/Azure/azure-sdk-for-net/issues/13938))
- [x] Azure.Messaging.EventHubs Readme issues ([#15303](https://github.com/Azure/azure-sdk-for-net/issues/15303))
- [x] Azure.Messaging.EventHubs.Processor Readme issue ([#15308](https://github.com/Azure/azure-sdk-for-net/issues/15308))
- [x] Samples ([#13939](https://github.com/Azure/azure-sdk-for-net/issues/13939))
