### ISSUE TITLE
Azure Cognitive Search October Release

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#14874]
### Features
- [ ] Continuation token bug
- [ ] Advanced batch support
- [x] Spatial types support
- [x] JSON Converters (Newtonsoft plugin for Spatial)
    - [ ] Expose existing converters to allow customers to use them
- [x] Expose IndexParameters
- [ ] More samples 
- [x] Scoring profile
