### ISSUE TITLE
Event Hubs Client Library for .NET - November Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#14913]
For general summary and goals, please see: [Release Event Hubs Track 2 Updates (#1393)](https://github.com/Azure/azure-sdk/issues/1393).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone
- [x] Design Proposal for Samples and Snippets Overhaul ([#11091](https://github.com/Azure/azure-sdk-for-net/issues/11091))
- [x] Design for a ConnectionStringBuilder Abstraction ([#12564](https://github.com/Azure/azure-sdk-for-net/issues/12564))

# Implementation

- [x] EventHubException ToString() Has No Helping Details ([#15894](https://github.com/Azure/azure-sdk-for-net/issues/15894))
- [x] Samples and Snippets Overhaul ([#15612](https://github.com/Azure/azure-sdk-for-net/issues/15612))
- [x] Revisit `EventHubsSharedKeyCredential` ([#9048](https://github.com/Azure/azure-sdk-for-net/issues/9048))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Document client lifetime guidance ([#15102](https://github.com/Azure/azure-sdk-for-net/issues/15102))
- [x] Reference documentation ([#14914](https://github.com/Azure/azure-sdk-for-net/issues/14914))
- [x] Samples ([#14915](https://github.com/Azure/azure-sdk-for-net/issues/14915))
