### ISSUE TITLE
Track 2 Vision Library Work Tracking Issue

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#15056]
This issue tracks work identified to get Vision APIs to Track 2 state

Some issues are tracked in API View:
https://apiview.dev/Assemblies/Review/3d12b213d29745828e9f8bc67e623251
https://apiview.dev/Assemblies/Review/8da86bb416d743d48d3dd96969812b31

Additional high-level, cross-cutting issues/questions:

**More Urgent/Ambiguous**

- [ ]  What "Clients" types should this library have? Should Device, Tracker include the Client name?
- [ ]  What's the auth story and specifically AAD support?
- [ ]  What is the right eventing model for this API for integration with other components?
- [ ]  What is the functional overlap with other vision libraries, key points of integration?
- [ ]  How is functionality spread across cloud/device?

**Less Urgent/Straightforward** 

- [ ]  The library needs to support mocking
- [ ]  Generic names need to be removed, e.g. BGRA, Image, Logger, Device
- [ ]  What namespace should we use?
- [ ]  Support distributed tracing, logging, telemetry
- [ ]  Add cancellation tokens to all APIs that do I/O

(This issue is modeled after @KrzysztofCwalina's https://github.com/Azure/azure-sdk-for-net/issues/13122 issue for Speech.)
