### ISSUE TITLE
November release of Key Vault for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15669]
# Features

- [ ] Secure key release
- [ ] Local cryptography (as many algorithms - including new - as possible)

# Testing

- [ ] Secure key release
- [ ] Local cryptography
- [ ] Set up CI tests for Admin package (#15066)
   - [ ] Backup/restore
   - [ ] RBAC

# Reviews

- [ ] Arch Board review for Secure Key Release
- [ ] API unification meeting
   - [ ] `KeyVaultBackupClient`
   - [ ] `KeyVaultAccessControlClient`
   - [ ] `LocalCryptographyClient`

**Comment by heaths** [comment]
Released.
