### ISSUE TITLE
Address feedback from UX studies for 5.1.0-beta.x

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#15809]
- [ ] Add visual to the documentation to explain the mined opinions structure and naming better. i.e. Small graphic with opinion, sentence etc. in sample #16362
- [ ] Change `documents` in all batch samples to have multiple sentences instead of one. #16361
- [x] Consider improving the docstrings for all the Options bag in the SDK to include what type of options are there. #16281
- [ ] Improve how we surface in the debugger properties that are in `xxCollection` types so they don't get lost in the Raw view area. #16283
- [ ] Adding helper method to get opinions? Is helper method for optional property feasible? Will removing details about offset/length will cause confusion in the future? What is the priority of adding helper methods? #16284
- [x] Improve `IsNegated` docstring to include how this affects the sentiment of the `Opinion`. #16281

**Comment by maririos** [comment]
>Consider improving the docstrings for all the Options bag in the SDK to include what type of options are there.

PR https://github.com/Azure/azure-sdk-for-net/pull/16281

>Improve IsNegated docstring to include how this affects the sentiment of the Opinion.

PR https://github.com/Azure/azure-sdk-for-net/pull/16281

**Comment by maririos** [comment]
>Improve how we surface in the debugger properties that are in xxCollection types so they don't get lost in the Raw view area.

Issue https://github.com/Azure/azure-sdk-for-net/issues/16283 created

**Comment by maririos** [comment]
>Adding helper method to get opinions? Is helper method for optional property feasible? Will removing details about offset/length will cause confusion in the future? What is the priority of adding helper methods?

Issue https://github.com/Azure/azure-sdk-for-net/issues/16284 created

**Comment by maririos** [comment]
>Change documents in all batch samples to have multiple sentences instead of one.

Issue https://github.com/Azure/azure-sdk-for-net/issues/16361

**Comment by maririos** [comment]
Issues have been created for all work item. Will follow up progress in each individual one.
