### ISSUE TITLE
Event Hubs Client Library for .NET - February Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#16628]
For general summary and goals, please see: [Release Event Hubs Track 2 Updates (#1393)](https://github.com/Azure/azure-sdk/issues/1393).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Event Hubs Test Pipelines: Split out Management, Legacy Client, and Client Tests ([#15101](https://github.com/Azure/azure-sdk-for-net/issues/15101))
- [x] Partition checkpoint retrieval can be optimized ([#17386](https://github.com/Azure/azure-sdk-for-net/issues/17386))
- [x] Custom Endpoint Address Support ([#12555](https://github.com/Azure/azure-sdk-for-net/issues/12555))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Azure.Messaging.EventHubs Readme issue ([#17616](https://github.com/Azure/azure-sdk-for-net/issues/17616))
- [x] Processor Configuration Sample: Detail Load Balancing Configuration ([#17680](https://github.com/Azure/azure-sdk-for-net/issues/17680))
- [x] Reference documentation ([#16629](https://github.com/Azure/azure-sdk-for-net/issues/16629))
