### ISSUE TITLE
Event Hubs Client Library for .NET - March Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#17678]
For general summary and goals, please see: [Release Event Hubs Track 2 Updates (#1393)](https://github.com/Azure/azure-sdk/issues/1393).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Event Hubs: Performance Test Starter Kit ([#18541](https://github.com/Azure/azure-sdk-for-net/issues/18541))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Event Hubs: Reformat Migration Guide ([#15586](https://github.com/Azure/azure-sdk-for-net/issues/15586))
- [x] Add Thread Safety and Additional Concepts README sections to Event Hubs and Service Bus ([#18548](https://github.com/Azure/azure-sdk-for-net/issues/18548))
- [x] Reference documentation ([#17679](https://github.com/Azure/azure-sdk-for-net/issues/17679))
