### ISSUE TITLE
March release of Key Vault for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#18444]
## Features

- [ ] RBAC including custom role definitions
- [ ] Full/selective backup/restore
- [ ] AES key support
- [ ] Public exponent authoring for RSA keys

## Tasks

- [ ] Documentation
- [ ] Performance tests
- [ ] Archboard API review for upcoming GA

**Comment by heaths** [comment]
Duplicate of #18758
