### ISSUE TITLE
Event Hubs Client Library for .NET - April Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#18534]
For general summary and goals, please see: [Messaging - Event Hubs for .NET (January-June 2021) (#18771)](https://github.com/Azure/azure-sdk-for-net/issues/18771).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Accept the Azure.Core Shared Key and SAS Credentials ([#16418](https://github.com/Azure/azure-sdk-for-net/issues/16418))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#18535](https://github.com/Azure/azure-sdk-for-net/issues/18535))
