### ISSUE TITLE
Track 2 ACR Library Work Tracking Issue

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#18579]
This issue tracks work identified to get Track 1 API library to Track 2 state

Additional API-level issues are tracked in APIView in progress: https://apiview.dev/Assemblies/Review/9c5900f8545342ba9a6b00cd7802839c

API prototyping branch is here: https://github.com/Azure/azure-sdk-for-net/compare/master...annelo-msft:annelo/acr-experiment-3

### Bigger
- [x] Determine which [functional scenarios](https://gist.github.com/annelo-msft/4ac907517f98c67dff3420b465e43c0d) will be  most common for ACR SDK customers, and which are "long-tail" use cases
  - Working with service team on this.
- [ ] Implement challenge-based auth flow, see [this PR](https://github.com/Azure/azure-sdk-for-net/compare/master...christothes:users/chriss/CAE-KeyVault?expand=1#diff-8b6e5ca4150bc0fabc405902879d052c2821e67c8b45ca3f0f7e7a5247263836) for an example -- will this Identity type work for ACR?
- [x] Make metadata operations look like [Cosmos API](https://apiview.dev/Assemblies/Review/0de57f00b1ad4fdab2fa218f59863c78)?
  - Only editable meta-data properties are permissions, so we won't copy Cosmos until there is a richer query syntax
- [x] Make blob operations look like [Storage Block Blob APIs](https://apiview.dev/Assemblies/Review/77426af3f12a4487ab98859fca53a6dc#Azure.Storage.Blobs.Specialized.BlockBlobClient)?
  - only in the sense that we'll upload chunks; otherwise we'll expose the storage APIs in a way that's close to the Docker v2 REST APIs since this is a very specific flow; we'll move these to an advanced namespace to hide them from Day 0 customers.
- [ ] Client Hierarchy based on storage APIs?  (Follow guidance in [.NET guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-hierarchy))
  - Outstanding question: Should we have Tag and Manifest clients?
  - Suggest: No.  Tag client would be fine, but would only have a few operations.  Manifest client would necessarily have us putting Manifest operations and polymorphic hierarchy on a type that's really two types: Manifest metadata operations and Manifest file operations.  I'm flexible on this one.
- [ ] How best to model manifests for ease of use vs. need for schema-specific types?
  Notes: Is there a use-case that would motivate breaking ManifestWrapper into polymorphic schema-specific types?  Yes - there are samples in the azure-cli where we [deserialize to a schema-specific type](https://github.com/sajayantony/acr-cli/blob/main/Services/ContentStore.cs#L85), and where we [new a schema-specific type explicitly](https://github.com/sajayantony/acr-cli/blob/main/Services/ContentStore.cs#L149).  Beyond this, are there schema-specific use cases we can't achieve when an operation is returning ManifestWrapper instead of a schema-specific manifest?  We'll need to clarify with the service team that multiple manifest schemas aren't actually returned for ManifestWrapper.
- [ ] Update current samples that do "call method/print to console" to sketch out intent of API in hero scenarios
- [ ] Identify whether there is anything non-standard about how errors are returned by the ACR service
- [x] Design for [Notary story](https://docs.docker.com/notary/getting_started/)
- [ ] Verification based on digest e.g. [for blob upload/download](https://github.com/sajayantony/acr-cli/blob/main/Services/RegistryService.cs#L105)... should we handle this for the caller so they don't have to? ... if digests don't match, is throwing an exception sufficient?
- [ ] Work on swagger - go through code generator transforms and shift these into swagger file directly or autorest.md

### Bigger/Phase 2
- [X] Design around data plane tasks API
  - out of scope for ACR v1
- [X] Design around APIs not documented in the [ACR swagger file](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerregistry/data-plane/Microsoft.ContainerRegistry/preview/2019-08-15/containerregistry.json)
  - out of scope for ACR V1; we'll need to add a few endpoint/operations to the swagger file that are missing
- [ ] Designs around ACR V2 APIs like ACR Recover API and others

### Smaller
- [ ] Is there value in modeling Digest as Byte[] ?
- [ ] How best to model Content Descriptor? (See discussion section below)  Is there a use-case to motivate using polymorphism and strongly typing the different descriptor types where they're found on manifests?  e.g. what would happen if we set the `Annotations` field on a DockerConfigDesciptor (since it's supported on the current `Descriptor` type), and then we tried to upload it?  Would we lose data?  If we wanted to do this, how much would we need to change the swagger/or is it supported in code gen?
- [ ] Add x-ms-pageable blocks to swagger to generate pageable methods.
- [x] Add constructors to clients to support non-TokenCredential auth types, if needed.
- [ ] Add "monolithic upload in one request" operation to the swagger file so we get it in code-gen (see "POST INITIATE BLOB UPLOAD" under[ Initiate Blob Upload](https://docs.docker.com/registry/spec/api/#initiate-blob-upload) for details.
- [ ] Investigate: is specifying Range header as input parameter incorrect, where Content-Range header should be used for input and Range used for output instead?

#### Content Descriptor
There are (at least) four different formats for content descriptor:

- `DockerConfigDescriptor` // https://docs.docker.com/registry/spec/manifest-v2-2/#image-manifest-field-descriptions
- `DockerLayerDescriptor` // https://docs.docker.com/registry/spec/manifest-v2-2/#image-manifest-field-descriptions
- `DockerManifestDescriptor` // https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list
- `OciContentDescriptor` // https://github.com/opencontainers/image-spec/blob/master/descriptor.md

**Comment by annelo-msft** [comment]
The work on this library is currently tracked with other issues.

@AlexGhiondea FYI
