### ISSUE TITLE
Update Analyze samples

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#18678]
In sample.cs files:

- [x] Sample should also show operation information like `CreatedOn`, `ExpiresOn`, `TotalActions` etc... PR #19243
- [ ] Sample should check that there were no errors in the action and in the document. for document level example, see [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample5_RecognizePiiEntities.md#recognizing-personally-identifiable-information-in-multiple-documents).

[sample.md](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample_AnalyzeBatchActions.md):
- [ ] Name needs to change to `Sample_AnalyzeBatchActions or `Sample7_`?.
- [x] Remove the word asynchronously from the description.  PR #19243
- [x] Description of the content needs to be updated to reflect the new names (ie. use `StartAnalyzeBatchActions` instead of `StartAnalyzeOperationBatchAsync` PR #19243

**Comment by maririos** [comment]
The new blog post include links to Analyze sample so we can't rename them anymore :(
