### ISSUE TITLE
Azure Key Vault for .NET (January-June 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#18758]
## Features

- [x] RBAC including custom role definitions
- [x] Full/selective backup/restore
- [x] AES key support
- [x] Public exponent authoring for RSA keys

## Tasks

- [x] Documentation
- [x] Performance tests
- [x] Archboard API review for upcoming GA

**Comment by heaths** [comment]
Keys, Secrets, and Certs shipped 4.2, and Admin shipped 4.0.
