### ISSUE TITLE
Azure.Identity Improvements for .NET (January-May 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#18765]
### Azure.Identity February, March, and April 2021 Releases
- [x] Complete [CAE](https://github.com/Azure/azure-sdk-pr/issues/192) Support
    - [x] Finish Testing Continuous Access Evaluation based on [test plan](https://gist.github.com/schaabs/be730e1b3b72fcf101b5b21285428ded)
        - [x] Calling Revoke Sessions
        - [x] IP Restrictions
        - [x] Client network configuration sends RP and STS calls from different IP address
    - [x] Refactor CAE logic from azure-core to azure-resourcemanager-core
    - [x] Port CAE performance test from Java PR
- [x] Complete Token Cache / Authentication API Changes
    - The API diff for .NET which includes the token cache redesign included with the added user can be found [here](https://apiview.dev/Assemblies/Review/d0854ffa887a4b35b24d91ecb6d7a40c?diffRevisionId=949f556c4d904455bb6227372ab8c57a&doc=False&diffOnly=False).  The implementation is already merged to master with the bulk of the implementation in [TokenCache.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/TokenCache.cs) and [PersistentTokenCache.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/PersistentTokenCache.cs).
    - The champion scenarios are availabe in the .NET samples:
        - [Persisting the credential TokenCache](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/samples/TokenCache.md)
        - [Client side user authentication](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md)
    - Also the python changes related to the redesign can be found [here](https://github.com/Azure/azure-sdk-for-python/pull/16326), and the equivalent champion scenarios can be found in [token_cache_sample.md](https://gist.github.com/chlowell/17bfe9b5db26280d7649b107f4c67142).
    - [x] Port performance test from Java PR
- [x] Complete final Archboard consistency review
- [x] Review and update README.md and the Getting Started Guide 
    - [x] Update "Next Steps" section
    - [x] Update sections to add new features / champion scenarios shipped in the February and March releases
