### ISSUE TITLE
Event Hubs Client Library for .NET - May Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#19299]
For general summary and goals, please see: [Messaging - Event Hubs for .NET (January-June 2021) (#18771)](https://github.com/Azure/azure-sdk-for-net/issues/18771).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Event Hubs: Performance Tests for Microsoft.Azure.EventHubs ([#20099](https://github.com/Azure/azure-sdk-for-net/issues/20099))
- [x] Event Processor: Move Partition Initialization into a Background Task ([#18544](https://github.com/Azure/azure-sdk-for-net/issues/18544))
- [x] Sample: Custom Event Processor ([#17686](https://github.com/Azure/azure-sdk-for-net/issues/17686))
- [x] Event Processor Client: Eagerly Validate Connections at Startup ([#19301](https://github.com/Azure/azure-sdk-for-net/issues/19301))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#19300](https://github.com/Azure/azure-sdk-for-net/issues/19300))
