### ISSUE TITLE
Azure Monitor OpenTelemetry Exporter for .NET (January - June 2020)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#19389]
This epic tracks the work required by the Azure SDK team to support the [OpenTelemetry](https://opentelemetry.io/) 1.0/stable release in .NET

- [ ] Update Azure.Core to the latest OpenTelemetry 1.0/stable release
- [ ] Test for OpenTelemetry breaking changes by collecting plain text and Jaeger traces for REST based SDKs (ex: Storage)
    - [ ] File Azure SDK tracking issues & fix bugs to become complaint with the latest OpenTelemetry specification
- [ ] Test for OpenTelemetry breaking changes by collecting plain text and Jaeger traces for AMQP based SDKs (ex: Service Bus)
    - [ ] File Azure SDK tracking issues & fix bugs to become complaint with the latest OpenTelemetry specification
- [ ] Collect portal snapshots for REST and AMQP based SDKs and compare results against Jaeger
    - [ ] File Azure Monitor tracking issues on traces that are not exported / displayed correctly

**Comment by jsquire** [comment]
Closing; the milestone has passed and no associated issues remain open.
