### ISSUE TITLE
Event Hubs Client Library for .NET - June Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#20094]
For general summary and goals, please see: [Messaging - Event Hubs for .NET (January-June 2021) (#18771)](https://github.com/Azure/azure-sdk-for-net/issues/18771).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Event Hubs: Fix Unobserved Stolen Partitions ([#21297](https://github.com/Azure/azure-sdk-for-net/issues/21297))
- [x] Investigate Force-Closing AMQP Links for Cancellation ([#19306](https://github.com/Azure/azure-sdk-for-net/issues/19306 ))
- [x] Extend logging for AMQP Connection/Link create and close scenarios ([#20949 ](https://github.com/Azure/azure-sdk-for-net/issues/20949 ))
- [x] Expose additional transport configuration in `ConnectionOptions` ([#21482 ](https://github.com/Azure/azure-sdk-for-net/issues/21482 ))
- [x] [Flaky test] CreatePartitionProcessorDoesNotAllowReadingLastEventPropertiesWithNoConsumer ([#21295](https://github.com/Azure/azure-sdk-for-net/issues/21295))

# Release and Documentation

- [x]  Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x]  Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#20096](https://github.com/Azure/azure-sdk-for-net/issues/20096))
