### ISSUE TITLE
Event Hubs Client Library for .NET - August Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#21631]
For general summary and goals, please see: [Azure Event Hubs Commitments for .NET (July-December 2021) (#22171)](https://github.com/Azure/azure-sdk-for-net/issues/22171).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Event Hubs: Client Type Identifier Support ([#20101](https://github.com/Azure/azure-sdk-for-net/issues/20101))
- [x] Expose additional idle timeout configuration in ConnectionOptions ([#22674](https://github.com/Azure/azure-sdk-for-net/issues/22674))
- [x] Event Hubs: Update snippet replacement syntax ([#22435](https://github.com/Azure/azure-sdk-for-net/issues/22435))
- [x] Event Hubs: Remove unused snippets ([#22123](https://github.com/Azure/azure-sdk-for-net/issues/22123))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#21632](https://github.com/Azure/azure-sdk-for-net/issues/21632))
- [x] Clients Sample: Extend with new ConnectionOptions ([#21633](https://github.com/Azure/azure-sdk-for-net/issues/21633))
