### ISSUE TITLE
Nickel Community Feature Requests related to StaticTokenCredential / token helper methods

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#21940]
Tracking Item to review the top customer-requested enhancements from the previous semester.  We will prioritize this list and fit in as many as possible in the final coding milestone of this semester (After all must-have features are completed first).  See @g2vinay and @jongio 

Ex unordered short list:

   - [ ] **Feature: Expose Credential type for DefaultAzureCredential and ChainedTokenCredential**
    - Enables users know which credential type is being used. [#8948](https://github.com/Azure/azure-sdk-for-net/issues/8948)
   - [ ] **Feature: Add new StaticTokenCredential type ([prototype PR](https://github.com/jongio/azidext/pull/41))**
    - Encapsulate an AAD credential with a prefetched token for an AAD application.
   - [ ] Request: Add support for fetching an access token from a refresh token
   - [ ]  Request: provide the functionality of building a token credential from (a: existing credential, b: tenant id) for refresh token based credentials: InteractiveBrowserCredential and DeviceCodeCredential, VisualStudioCodeCredential ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))
   - [ ]  Request: provide the functionality of setting tenant id for AzureCliCredential ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))
   - [ ]  Request: provide a valid token in VisualStudioCodeCredentialBuilder without tenant id, use this token we can list the tenants ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))
   - [ ]  Request: provide the functionality of listing cached account(azure environment, tenant id, user name, client id) for SharedTokenCacheCredential ([request](https://github.com/Azure/azure-sdk-for-java/issues/19443))

**Comment by christothes** [comment]
TenantId for `AzureCliCredential` will be implemented when https://github.com/Azure/azure-sdk-for-net/pull/21378 merges

**Comment by christothes** [comment]
#23680

**Comment by joshfree** [comment]
> ** Improve Azure Identity SDK Error Messages and logging details Improve The Azure Identity Error messages and logging details #23648

@christothes / @schaabs can you follow up?

**Comment by joshfree** [comment]
Can this be closed out now?
