### ISSUE TITLE
Azure Event Hubs Commitments for .NET (July-December 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#22171]
[Azure Event Hubs](https://docs.microsoft.com/azure/event-hubs/event-hubs-about) is a highly scalable publish-subscribe service that can ingest millions of events per second and stream them to multiple consumers. This lets you process and analyze the massive amounts of data produced by your connected devices and applications. 

The [Azure.Messaging.EventHubs](https://www.nuget.org/packages/Azure.Messaging.EventHubs) & [Azure.Messaging.EventHubs.Processor](https://www.nuget.org/packages/Azure.Messaging.EventHubs.Processor) packages provides the SDK for .Net developers to write applications that use Azure Event Hubs. Version 5 of this package follows the latest [guidelines for writing C# .Net SDKs for Azure services](https://azure.github.io/azure-sdk/dotnet_introduction.html) with the goal of being  a client library that is developer-friendly, idiomatic to the .Net ecosystem, and as consistent across different languages and platforms as possible.

This issue tracks the work we have planned for this package for the duration of July - December 2021

### New features
- [ ] Design & implement a buffered producer that allows users to queue events to be sent with implicit batching that happens behind the scenes
- [ ] Add the idempotent producer feature as described in https://gist.github.com/jsquire/1cc4db6b3ca4ef13d26dc5315483555b to the new buffered producer

### Testing improvements:
- [ ] Update stress tests to use the new infrastructure where we now containerize the tests and have automation to run the tests on a scheduled basis
- [ ] Update perf tests to use the perf test framework that will then allow them to be automated

### General improvements:
- Fix incoming customer reported issues
- Build Trouble Shooting Guides
