### ISSUE TITLE
Event Hubs Client Library for .NET - September Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#22415]
For general summary and goals, please see: [Azure Event Hubs Commitments for .NET (July-December 2021) (#22171)](https://github.com/Azure/azure-sdk-for-net/issues/22171).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Sample for demonstrating the use of AzureEventSourceListener with Event Hubs logging ([#11763](https://github.com/Azure/azure-sdk-for-net/issues/11763))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#22416](https://github.com/Azure/azure-sdk-for-net/issues/22416))
- [x] Extend Doc Comments with Common Exception Scenarios ([#19305](https://github.com/Azure/azure-sdk-for-net/issues/19305))
