### ISSUE TITLE
Event Hubs Client Library for .NET - November Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#23816]
For general summary and goals, please see: [Azure Event Hubs Commitments for .NET (July-December 2021) (#22171)](https://github.com/Azure/azure-sdk-for-net/issues/22171).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] [Flaky test] LoadBalancingAppliesTheBalancedStrategy ([#24343](https://github.com/Azure/azure-sdk-for-net/issues/24343))
- [x] EventHubBufferedProducerClient: Infrastructure and Functionality ([#23480](https://github.com/Azure/azure-sdk-for-net/issues/23480))
- [x] EventHubBufferedProducerClient: Partition Assignment ([#23481](https://github.com/Azure/azure-sdk-for-net/issues/23481))
- [x] EventHubBufferedProducerClient: Flush and Clear ([#23482](https://github.com/Azure/azure-sdk-for-net/issues/23482))
- [x] EventProducerClient: Update Summary Doc Comments ([#23485](https://github.com/Azure/azure-sdk-for-net/issues/23485))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to Nuget for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to Nuget for features in the previous milestone
- [x] Reference documentation ([#23817](https://github.com/Azure/azure-sdk-for-net/issues/23817))
