### ISSUE TITLE
[ACR] [BlobClient] Updates to ACR 1.1.0 API

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#23822]
The API review for the proposed ACR v1.1.0-beta.1 API is here: https://apiview.dev/Assemblies/Review/ba57bf904e524ce3bf647dad124ddc7c/31eae60547cc4c42a26a98a95cd310aa?doc=False

Items to address from this review include:
- [ ] Remove `AzureResourceManagerGermany` from `ContainerRegistryAudience` enum (will need to happen across languages)
- [ ] Consider naming of `ContainerRegistryBlobClient`, given this handles manifests as well.
- [ ] Add extension method to enable getting `ContainerRegistryBlobClient` from main client
- [ ] Move `repository` before `credential` in blob client constructor
- [ ] Rename `DownloadManifest` to `GetManifest`
- [ ] Provide a `string path` overload to `UploadBlob`
- [ ] Make `tag` an optional param on the `UploadManifest` method instead of using `UploadManifestOptions` (since the guidelines suggest six to use an options bag)
- [ ] Change `Url` property in `OciAnnotations` to `Uri` and make it a proper `Uri` type
- [ ] Consider making `OciBlobDescriptor.MediaType` an extensible enum.  This is the media type of the blob not the manifest, so there may not be a clear set of possible types.
- [ ] Change name of `OciManifest.Config` to `OciManifest.Configuration`

**Comment by Mohit-Chakraborty** [comment]
Assigning to myself to verify all items are addressed across the different languages.

**Comment by jsquire** [comment]
@Mohit-Chakraborty:  If you'd be so kind, please remove from the October milestone.
