### ISSUE TITLE
Azure SDK MQ 2021 work for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#24088]
This tracks the Azure SDK MQ 2021 work for .NET

Areas of investment
  - [ ]  Doc clean-up
    - [ ] Readme improvements
    - [x] Improvements of the doc pipeline (#18077)
    - [ ] Documentation for F# developers (#18322) 
    - [ ] Add high quality comments to complex parts of our code base
    - [ ] Fix spelling errors in code
  - [ ] Engineering system improvements
    - [ ] Updates around our snippet generation (#20431, #20432)
    - [ ] Implement additional code analyzers
    - [ ] Update .NET test matrix 
    - [ ] Complete the Cred scan clean-up
  - [ ]  Test improvements
    - [ ] Move to the new test proxy infrastructure (#24167)
    - [ ] Implement smoke tests (#24168)
    - [ ] Improve test pass rate 
    - [ ] Migrate Event Hubs to the stress test framework
