### ISSUE TITLE
Text Analytics Client Library for .NET - February Milestone

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#25040]
For general summary and goals, please see: [Language Pillar Commitments for Text Analytics 3.2 (July 2021-March 2022) [#3080]](https://github.com/Azure/azure-sdk/issues/3080).  The work items linked to this issue herein represent the tasks needed to produce the .NET Text Analytics client library for the current milestone.

# Design, Review, and Planning

- [ ] Create issues and perform resource planning for the next milestone

# Implementation

- [ ] [Text Analytics] Add a sample for setting model version ([#25898](https://github.com/Azure/azure-sdk-for-net/issues/18520)) ([#25898](https://github.com/Azure/azure-sdk-for-net/issues/18520))
- [ ] [Text Analytics] Add a sample for setting model version ([#25898](https://github.com/Azure/azure-sdk-for-net/issues/25898))
- [ ] Add x-ms-enum.modelAsString=false to single value enums in Azure.AI.TextAnalytics ([#24633](https://github.com/Azure/azure-sdk-for-net/issues/24633))
- [ ] Use dynamic resources for the custom features ([#24928](https://github.com/Azure/azure-sdk-for-net/issues/24928))
- [ ] Use a dynamic resource for our live tests ([#25041](https://github.com/Azure/azure-sdk-for-net/issues/25041))
- [ ] Create a TextAnalyticsProject bag containing the ProjectName and DeploymentName ([#25056](https://github.com/Azure/azure-sdk-for-net/issues/25056))
- [ ] Test our library against the new language API ([#25057](https://github.com/Azure/azure-sdk-for-net/issues/25057))
- [ ] Look into discoverability of extractive summarization and custom features that are only exposed under the Analyze method ([#25091](https://github.com/Azure/azure-sdk-for-net/issues/25091))
- [ ] Diagnose/investigate timeouts on TA live tests ([#25152](https://github.com/Azure/azure-sdk-for-net/issues/25152))

# Release and Documentation

- [ ] Perform any needed release of the Text Analytics package to NuGet for features in the previous milestone
