### ISSUE TITLE
Event Hubs Client Library for .NET - February Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#25195]
For general summary and goals, please see: [Azure Event Hubs Commitments (July 2021-March 2022) [#3078]](https://github.com/Azure/azure-sdk/issues/3078).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone
- [x] Architect discussion:  batching options for Event Processor Client
- [x] Update documentation on MS Docs for `host.json` options available to the Function bindings. ([#87606](https://github.com/MicrosoftDocs/azure-docs/pull/87606))

# Quality

- [x] [Flaky Test] Event Hubs Function Bindings: EventHub_PartitionKey ([#23484](https://github.com/Azure/azure-sdk-for-net/issues/23484))
- [x] [Flaky Test] Event Hubs Function Bindings: EventHub_InitialOffsetFromEnqueuedTime ([#21298](https://github.com/Azure/azure-sdk-for-net/issues/21298))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to NuGet for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to NuGet for features in the previous milestone
- [x] Reference documentation ([#25196](https://github.com/Azure/azure-sdk-for-net/issues/25196))
