### ISSUE TITLE
Form Recognizer Client Library for .NET - March Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26266]
For general summary and goals, please see: [Azure Form Recognizer Commitments (July 2021-March 2022) [#3067]](https://github.com/Azure/azure-sdk/issues/3067).  The work items linked to this issue herein represent the tasks needed to produce the .NET Form Recognizer client library for the current milestone.

# Design, Review, and Planning

- [ ] Create issues and perform resource planning for the next milestone

# Implementation

- [ ] Placeholder ([#00000](https://github.com/Azure/azure-sdk-for-net/issues/00000))

# Release and Documentation

- [ ] Perform any needed release of the Form Recognizer package to NuGet for features in the previous milestone
