### ISSUE TITLE
Text Analytics Client Library for .NET - March Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26263]
For general summary and goals, please see: [Language Pillar Commitments for Text Analytics 3.2 (July 2021-March 2022) [#3080]](https://github.com/Azure/azure-sdk/issues/3080).  The work items linked to this issue herein represent the tasks needed to produce the .NET Text Analytics client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone
- [x] Proposal for supporting the new language service APIs for archboard review ([#3774](https://github.com/Azure/azure-sdk/issues/3774))

# Implementation

- [x] [Look into discoverability of extractive summarization and custom features that are only exposed under the Analyze method ([#25091](https://github.com/Azure/azure-sdk-for-net/issues/25091))
- [ ] [Text Analytics] Add a sample for setting model version ([#25898](https://github.com/Azure/azure-sdk-for-net/issues/25898))
- [x] [Text Analytics] Prototype Side-by-Side CodeGen Layer ([#26855](https://github.com/Azure/azure-sdk-for-net/issues/26855))
- [ ] [Text Analytics] Prototype Abstraction for Service Interactions ([#26856](https://github.com/Azure/azure-sdk-for-net/issues/26856)) _(start now; will complete in April)_

# Release and Documentation

- [x] Perform any needed release of the Text Analytics package to NuGet for features in the previous milestone
