### ISSUE TITLE
Event Hubs Client Library for .NET - March Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26265]
For general summary and goals, please see: [Azure Event Hubs Commitments (July 2021-March 2022) [#3078]](https://github.com/Azure/azure-sdk/issues/3078).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [ ] Create issues and perform resource planning for the next milestone

# Implementation

- [ ] Placeholder ([#000000](https://github.com/Azure/azure-sdk-for-net/issues/000000))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to NuGet for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to NuGet for features in the previous milestone
