### ISSUE TITLE
Release stable version Track 2 .Net Management SDKs

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#26387]
- [x] Azure.ResourceManager
- [x] Azure.ResourceManager.Resources
- [ ] Azure.ResrouceManager.KeyVault
- [ ] Azure.ResrouceManager.Compute
- [ ] Azure.ResrouceManager.Network
- [ ] Azure.ResrouceManager.Cdn
- [ ] Azure.ResrouceManager.Sql
- [ ] Azure.ResrouceManager.CosmosDB
- [ ] Azure.ResrouceManager.EventHubs
- [ ] Azure.ResrouceManager.ServiceBus
- [ ] Azure.ResrouceManager.Monitor
- [ ] Azure.ResrouceManager.AppConfiguration
- [ ] Azure.ResrouceManager.Communication
- [ ] Azure.ResrouceManager.WebPubSub

**Comment by ArthurMa1978** [comment]
Related EPICs
- https://github.com/azure/autorest.csharp/issues/1620
- https://github.com/Azure/autorest.csharp/issues/1788
- https://github.com/azure/autorest.csharp/issues/1756

**Comment by ArthurMa1978** [comment]
We moved to Projects https://github.com/orgs/Azure/projects/148/views/1, so close all epic issues
