### ISSUE TITLE
Text Analytics Client Library for .NET - April Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26833]
For general summary and goals, please see: [Language Pillar Commitments for Text Analytics 3.2 (July 2021-March 2022) [#3080]](https://github.com/Azure/azure-sdk/issues/3080).  The work items linked to this issue herein represent the tasks needed to produce the .NET Text Analytics client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] [Text Analytics] Prototype Side-by-Side CodeGen Layer ([#26855](https://github.com/Azure/azure-sdk-for-net/issues/26855))

# Release and Documentation

- [x] Perform any needed release of the Text Analytics package to NuGet for features in the previous milestone
