### ISSUE TITLE
Event Hubs Client Library for .NET - April Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26832]
For general summary and goals, please see:  [Azure Event Hubs Commitments (April 2022 - September 2022) [#3990]](https://github.com/Azure/azure-sdk/issues/3990).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Checkpoint store abstraction **_(NEEDS ISSUE)_**
- [x]  Revisit the ability to cache AMQP messages when adding events to the AmqpEventBatch ([#9569](https://github.com/Azure/azure-sdk-for-net/issues/9569))

# Release and Documentation

- [x] Perform any needed release of the Event Hubs core package to NuGet for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to NuGet for features in the previous milestone
