### ISSUE TITLE
Solve APIView comments for all batch 1 APIViews

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#27375]
- ResourceManager
    - [x] Ln13 Rename to `GetResourceClient` 
    - [x] Ln27 Rename `Provider` to `ResourceProvider`
    - [x] Ln73 Remove the namespace `Azure.ResourceManager.Core`
    - [x] Ln80,92 `DiagnosticOptions` to `DiagnosticsOptions`
    - [x] Ln95 Confirm if can fix
    - [x] Ln116 LRO change `waitFormComplete` to `enum` `WaitUntil`
    - [x] Ln117,132,134,138 Manually pack parameters into property bag
    - [x] Ln172 Change all Type property name to full name
    - [x] Ln 316 Remove `ErrorResponse`
    - [x] Ln 1118 Do we need to change `Alias` to `ResourceTypeAlias` ? and for all other `Alias*` type?
    - [x] Ln 1156 Rename `DataEffect` to `DataPolicyManifestEffect`
    - [x] Ln 1263 Rename `LockLevel` to `ManagementLockLeve`
    - [x] Ln 1272 Rename `ParameterDefinitionsValue` to `ArmPolicyParameter`
    - [x] Ln 1287 Rename `ParameterType` to `PolicyParameterType`
    - [x] Ln 1522 Rename `TrackedResourceExtended` to `ExtendedTrackedResourceData`
    - [x] [ProviderPermissionListResult](https://apiview.dev/Assemblies/Review/996e07cadc7449809982bc42ec445977/856c92e379ec4d9e88dc3176163ce31b#ebcdadf265334281aec0cbadb343e477)
    - [x] [ProviderResourceTypeListResult](https://apiview.dev/Assemblies/Review/996e07cadc7449809982bc42ec445977/856c92e379ec4d9e88dc3176163ce31b#9cd3380b4267415d8dfa103341a2dfc0)
    - [x] [ErrorDetail](https://apiview.dev/Assemblies/Review/996e07cadc7449809982bc42ec445977/856c92e379ec4d9e88dc3176163ce31b#d5d995bded4a445fbe2e3487865544da)

- ResourceManager.Resources
    - [x] Ln 8 Rename `Application` to `ArmApplication`
    - [x] Ln 361 move to one extension
    - [x] Ln 589 rename to `ArmDependency`
    - [x] [Rename: Parameter -> Data](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#fe8f858dbc084377a4b0797564f9ed45)
    - [x] [Rename: ArmApplicationPackageSupportUrls-> ArmApplicationPackageSupportUris](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#7c563541fae1474a8fe718361e1640b2)
    - [x] [Rename: AzurePublicCloud to AzurePublicCloudUri](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#1db7faeccff94499acc685ba802ca697)
    - [x] [Rename: SupportUrls -> SupportUris](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#c42fd187fc4b4698857e1a50e1bacef8)
    - [x] [*Rename: ArmApplicationDefinitionData -> ArmApplicationResourceData](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#55ba4b37e75247ff8d4732f475f43d40)
    - [x] [ErrorDetail](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#9d302fda4e1846c69280de1e8b9c93aa)
    - [x] [Rename: BasicDependency to BasicArmDependency](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#085febaea0834b7da1be3956b866375b)
    - [x] [Rename: ParametersLink to ArmDeploymentParametersLink](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#bd554db47d28436fa749b86443fd455a)
    - [x] [Rename: OnErrorDeployment to ErrorDeployment](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#c21b525c305f478dbffbbdf587ce9a0b)
    - [x] [Rename: TemplateLink to ArmDeploymentTemplateLink](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#8edb7a1686ff4385b24a689fbad883e8)
    - [x] [ErrorDetail](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#e6d661c715304423a753bf2c83c4c521)
    - [x] [Rename: CleanupOptions to ScriptCleanupOptions](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#e2f6908d4c264bc28954bd1e98ee97bf)
    - [x] [Rename: EnvironmentVariable to ScriptEnvironmentVariable](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#19a883493fbb4f7f9b2d10a2cb26bb6c)
    - [x] [ErrorDetail](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#444d710888ca4d4ebf9abc4c91a4deb0)
    - [x] [Rename: StorageAccountConfiguration to ScriptStorageConfiguration](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#3f205cc6994c4e2081748d9f408643a3)
    - [x] [Rename: ExpressionEvaluationOptionsScopeType to ExpressionEvaluationScope](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#c3824bc4d95a41ce9164b9dc20aa9776)
    - [x] [Rename: onErrorDeployment to ErrorDeployment](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#d589e6f0b1234442b42741d52b70a34b)
    - [x] [ErrorDetail](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#9adbc28be0304b2bb1163b3c3566da6c)
    - [x] [Rename: ChangeType to WhatIfChangeType](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#6b614536787640288d771551e7f37c0b)
    - [x] [Rename: PropertyChangeType to WhatIfPropertyChangeType](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#161703b7865944e784334fd503906c04)
    - [x] [Rename: ProvisioningOperation to ProvisioningOperationKind](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#ec42386f81c54e5c9c4b583d4f061fba)
    - [x] [Rename: Parameter -> Data](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#ab95e4fcb7a94e1c81ec24b4e3072201)
    - [x] <del>[Rename: Duration to Interval](https://apiview.dev/Assemblies/Conversation/4455ff2a86cd43678e4dfc8b77cce8a5#60f427022403473d9dc13ac6b5c10e62)</del>
    - [x] [ResourceType](https://apiview.dev/Assemblies/Conversation/996e07cadc7449809982bc42ec445977#73ba51eac88648a09ac2a7221e2a0113)

- Common
    - [x] [`Sku` to `<RP name>Sku`](https://github.com/azure/azure-sdk-for-net/issues/27371)
    - [x] Object to BinaryData

**Comment by fengzhou-msft** [comment]
PR to address Resources comments: #27580

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/27478

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/27795
