### ISSUE TITLE
Event Hubs Client Library for .NET - May Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#27380]
For general summary and goals, please see: [Azure Event Hubs Commitments (April 2022 - September 2022) [#3990]](https://github.com/Azure/azure-sdk/issues/3990).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Create issues and perform resource planning for the next milestone

# Implementation

- [x] Event Hubs: Buffered Producer Performance Tests ([#28052](https://github.com/Azure/azure-sdk-for-net/issues/28052))
- [x] Event Hubs Function Bindings: Enable tests ignored due to data binding failures ([#26889](https://github.com/Azure/azure-sdk-for-net/issues/26889))
- [x] Event Hubs: Restore Package References ([#27427](https://github.com/Azure/azure-sdk-for-net/issues/27427))

# Release and Documentation

- [x] Stress test runs to prepare for release
- [x] Perform any needed release of the Event Hubs core package to NuGet for features in the previous milestone
- [x] Perform any needed release of the Event Hubs processor package to NuGet for features in the previous milestone
