### ISSUE TITLE
Implement the ability to keep DPG Generation template up to date

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#27397]
I generated this API today: https://apiview.dev/Assemblies/Review/fe482cb7d6b549ee83b36915d9fcd417

It should not have a dependency on Azure.Core.Experimental.

Ideally, every time we made generator changes in the repo, they would update the template as well.

**Comment by chunyu3** [comment]
@annelo-msft I will check and remove dependency of 'Azure.Core.Experimental' if it is not needed. 
And I think the changes of DPG will not affect the template.

**Comment by annelo-msft** [comment]
It would be ideal if we could automate it.

**Comment by annelo-msft** [comment]
This may be solved by doing this: https://github.com/Azure/azure-sdk-for-net/issues/26590

**Comment by heaths** [comment]
Some of us have been maintaining sdk/template so we probably want to make sure any changes to sdk/template are first made to eng/templates/Azure.ServiceTemplate.Template prior.

A few issues I see:

* [ ] PR #27547 - add example of showing namespace imports per-library; not this includes some changes to the `dotnet new` template as shown in the PR. We need to create library-specific "Snippet:..." regions because they have to be unique throughout the repo.
* [ ] PR #27428 - get the latest autorest features if not already in eng/templates
* [ ] PR #26484 - show an example of both sync and async tests / sample snippets

**Comment by heaths** [comment]
Discussing offline, we may have different goals here. Since sdk/template is more for HLC projects and must be runnable for smoke testing, perhaps we keep sdk/template as-is. Still, the eng/template data plane template should have a test-resources.json as well as perf/ and stress/ folders for an ideal SDK.

**Comment by annelo-msft** [comment]
The DPG projects should have everything the HLC projects have, as all libraries start off as DPG libraries going forward.  We shouldn't think of these as two separate types of projects - we are working toward alignment of the library types.  We should use issues like this as an opportunity to find problems we need to solve as we work toward this alignment.

**Comment by heaths** [comment]
The problem is going to be that we want sdk/template to have a minimal implementation along with tests. It's not only a template, but also a best practices template and is used for smoke testing engsys changes (and even our repo, but that smoke testing is changing). There may be ways of doing this, but we might be overextending what the .NET templating engine is capable of. Or maybe we just need to fix up the eng/template templates and rename this folder to something else and leave it alone e.g. sdk/sample.
