### ISSUE TITLE
[Core] Add JSON Merge Patch support to JsonData

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-for-net#27402]
### Library name

core

### Please describe the feature.

To support JSON Merge Patch methods, .NET should implement a PatchBuilder.
- PatchBuilder will be implemented in core.
- PatchBuilder will accept name / values and "build" a RequestContent.
- Names can be "dotted" to set nested fields arbitrarily deep
- Builder methods will allow fields to be "added" or "removed" (set to null)
- "build" might be generic to allow checking that patch structure conforms to a particular class 

An update method can then support JSON Merge Patch by accepting a RequestContent body.

### Work items
- [x] Add JSON Merge Patch functionality to MutableJsonDocument https://github.com/Azure/azure-sdk-for-net/pull/38058
- [x] Add an analyzer to prevent use of MutableJsonDocument and related internal shared source outside Azure.Core https://github.com/Azure/azure-sdk-tools/pull/6642
- [ ] Move MutableJsonDocument and related to internal shared source
- [ ] Add helper types for IList, IReadOnlyList, IDictionary, IReadOnlyDictionary properties
- [ ] Add JSON Merge Patch item to [ModelSerializerFormat](https://apiview.dev/Assemblies/Review/77bdbcef49a3465fa96fac3fb745bf57#Azure.Core.Serialization.ModelSerializerFormat)

**Comment by annelo-msft** [comment]
Described verbally at minute 9 of [Recording](https://msit.microsoftstream.com/video/2bdb0840-98dc-94f5-63b2-f1ec5233d6ab)[MS INTERNAL ONLY]

**Comment by m-nash** [comment]
@KrzysztofCwalina It looks like our plan of record was to skip convenience methods for PATCH which would allow customers to give us a merge patch payload since RequestContent can accept anything.

It also sounds like in a second iteration we wanted to create a `PatchableBuilder` helper which would allow customers to easily create the merge patch json and the result of `.Build` would be a RequestContent so it could go straight into the protocol method.

Is that correct and do we have any initial design of `PatchableBuilder`?  If not I will put together some options here.

I also wanted to ask if we wanted to do a hybrid convenience method for patch that looked like this

```c#
//protocol shape
public Response Patch(RequestContent content, RequestContext context = default)

//convenience shape
public Response<Model> Patch(RequestContent content, CancellationToken token = default)
```

It seems deserializing the response should be simple enough and would still be a valuable convenience for customers while at the same time allow the same flexibility with RequestContent as the input vs some PatchModel.

**Comment by KrzysztofCwalina** [comment]
When I investigated the possibility of shipping strongly typed (model based) PATCH APIs last time, I ran into an issue of very high complexity of implementation of such PATCH-enabled models. Since then, we (@annelo-msft) implemented a general-purpose library that can track changes and easily generate JSON PATCH payloads. Given that, I wonder if we should not revisit our POR to expose all PATCH APIs as simple/raw RequestContent. 

The new general purpose API is basically a mutable JsonDocument-like API. I think it makes is trivial (relatively) to implement patchable models, e.g. 

```csharp
public class Model {
    MutableJsonDocument _doc;

    internal Model(BinaryData content) => _doc = MutableJsonDocument.Parse(content);

    public string Foo {
        get => _doc["foo"]; // we could cache this, at the cost of all writes going into both places (the cache and _doc)
        set => _doc["foo"] = value;
    }

    internal void WritePatch(Stream stream) => _doc.WriteTo(stream, 'p'); // this write JSON PATCH
```

@annelo-msft, what do you think?

**Comment by annelo-msft** [comment]
Yes, I think this is achievable with MutableJsonDocument.

**Comment by KrzysztofCwalina** [comment]
@tg-msft, thoughts?

**Comment by m-nash** [comment]
@KrzysztofCwalina what about the comment around returning a full `Response<Model>` vs `Response`?  PATCH convenience methods still take advantage of the strongly typed response but not a strongly typed model for request?

**Comment by KrzysztofCwalina** [comment]
> PATCH convenience methods can still take advantage of the strongly typed response but not a strongly typed model for request?

I probably don't understand something, but to me the PATCh convineince method would take advantage of the strongly typed model:

```csharp 
Model m = client.Get(...);
m.A = 5;
client.Patch(m);
```

**Comment by m-nash** [comment]
Spoke offline with @KrzysztofCwalina and we decided for the short term we will keep protocol only for PATCH until we flush out some of the details around using the MutableJsonDocument object.

/cc @srnagar

**Comment by annelo-msft** [comment]
This is being requested with some priority from the generator team: https://github.com/Azure/autorest.csharp/issues/2492#issuecomment-1583894515

A prerequisite to this work -- at least in the approach we are currently considering -- is completion of [the initial release of DynamicData](https://github.com/Azure/azure-sdk-for-net/issues/30717).

**Comment by LuChen-Microsoft** [comment]
Hi our ACS Chat team got the similar issue here : [ Teams discussion link ](https://teams.microsoft.com/l/message/19:7b87fb348f224b37b6206fa9d89a105b@thread.skype/1711135322919?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1711135322919&teamName=Azure%20SDK&channelName=Language%20-%20DotNet&createdTime=1711135322919)

The ACS Chat team is working on the implementation of a new property called retention policy. Retention Policy is an optional property in the Chat thread and we are trying to allow users to update it to null.
 
We have this Update class to which we've added the new optional property called DataRetention: [azure-sdk-for-net/sdk/communication/Azure.Communication.Chat/src/Generated/Models/UpdateChatThreadRequest.cs at 7e3911296bfd2c9860cb5016da67aab2ba0c5376 · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/blob/7e3911296bfd2c9860cb5016da67aab2ba0c5376/sdk/communication/Azure.Communication.Chat/src/Generated/Models/UpdateChatThreadRequest.cs)
 
The API expects it to be serialized to "DataRetention": null when the user wants to overwrite it to null. However when the user passes it as null like below, it doesn't get serialized and it stays the same:
 
```csharp
            var updateOptionsWithNullRetentionPolicy = new UpdateChatThreadPropertiesOptions();
            updateOptionsWithNullRetentionPolicy.RetentionPolicy = null;
 
            await chatThreadClient.UpdatePropertiesAsync(updateOptionsWithNullRetentionPolicy);
            var updateResponseWithNullRetentionPolicy = await chatThreadClient.GetPropertiesAsync();
            Assert.IsNull(updateResponseWithNullRetentionPolicy.Value.RetentionPolicy); ---> FAILS, stays the same
```
 
 
This is how the autogenerated serialization of the update method is currently implemented, which doesn't work as it skips the serialization of the DataRetention to null when the customer passes it as null:

```chsarp
internal HttpMessage CreateUpdateChatThreadPropertiesRequest(string chatThreadId, string topic, IDictionary<string, string> metadata, ChatRetentionPolicy retentionPolicy)
{
    var message = _pipeline.CreateMessage();
    var request = message.Request;
    request.Method = RequestMethod.Patch;
    var uri = new RawRequestUriBuilder();
    uri.AppendRaw(_endpoint, false);
    uri.AppendPath("/chat/threads/", false);
    uri.AppendPath(chatThreadId, true);
    uri.AppendQuery("api-version", _apiVersion, true);
    request.Uri = uri;
    request.Headers.Add("Accept", "application/json");
    request.Headers.Add("Content-Type", "application/merge-patch+json");
    UpdateChatThreadRequest updateChatThreadRequest = new UpdateChatThreadRequest()
    {
        Topic = topic,
    };
    if (metadata != null)
    {
        foreach (var value in metadata)
        {
            updateChatThreadRequest.Metadata.Add(value);
        }
    }
    var model = updateChatThreadRequest;
    var content = new Utf8JsonRequestContent();
    content.JsonWriter.WriteObjectValue(model);
    request.Content = content;
    return message;
}
```

**Comment by jsquire** [comment]
Per discussion thread here, there are no plans to create a strongly-typed PATCH surface.   The protocol-level patch described here is available in System.ClientModel's `JsonPatch" implementation.
