### ISSUE TITLE
Validation should be happened during  swagger review stage

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#27728]
Currently lots of the sdk issues are coming from the incorrect / not good swagger, so something we should do is fix them before coming into SDK stage.

- [x] 'Duration' check, as this [issue](https://github.com/Azure/azure-sdk-for-net/issues/26843) described, if a property is a real duration format then it should be marked as `"format": "duration"`, other wise its name should not contain 'duration'.
- [x] A resource model should not end with a 'Resource' suffix, and give a more reasonable name. _should be an error_
- [x] Single word model names are too generic and have high chance of collision with other RPs.
- [x] <del>Enum value 0 should be "None", check [this](https://github.com/Azure/autorest.csharp/issues/1960) for more information.</del>
- [x] The body parameter in patch operation should not be nullable, check [this](https://github.com/Azure/autorest.csharp/issues/1968) for more information.
- [x] 'Id' check, most of the resource ID is a GUID, but some are not, highly recommend to mark an 'Id' property to GUID format if it is a real GUID.
- [x] Avoid single property model.

**Comment by ArthurMa1978** [comment]
http://aka.ms/lintrulecandidate

**Comment by ArthurMa1978** [comment]
All have been submitted into Swagger Lint Rule Candidate form
