### ISSUE TITLE
Event Hubs Client Library for .NET - June Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#28024]
For general summary and goals, please see: [Azure Event Hubs Commitments (April 2022 - September 2022) [#3990]](https://github.com/Azure/azure-sdk/issues/3990).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [ ] Create issues and perform resource planning for the next milestone

# Implementation

- [ ] Update the azure-messaging-replication-dotnet repo to use Azure.Messaging.* packages ([#19154](https://github.com/Azure/azure-sdk-for-net/issues/19154))
- [ ] Samples for Mocking Client Types ([#7382](https://github.com/Azure/azure-sdk-for-net/issues/7382))

# Release and Documentation

- [ ] Perform any needed release of the Event Hubs core package to NuGet for features in the previous milestone
- [ ] Perform any needed release of the Event Hubs processor package to NuGet for features in the previous milestone

**Comment by jsquire** [comment]
Closing epic in anticipation of moving to Projects.
