### ISSUE TITLE
Text Analytics Client Library for .NET - May Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#28058]
For general summary and goals, please see: [Language Pillar Commitments for Text Analytics (April 2022-September 2022) [#4162]](https://github.com/Azure/azure-sdk/issues/4162).  The work items linked to this issue herein represent the tasks needed to produce the .NET Text Analytics client library for the current milestone.

# Design, Review, and Planning

- [ ] Create issues and perform resource planning for the next milestone
- [ ] [Text Analytics] Design Error Experience for Unsupported Fields and Operations in Legacy Versions ([#28060](https://github.com/Azure/azure-sdk-for-net/issues/28060))

# Implementation

- [ ] [Text Analytics] Prototype Abstraction for Service Interactions ([#26856](https://github.com/Azure/azure-sdk-for-net/issues/26856))
- [ ] [Text Analytics] Apply Service Abstraction to New Endpoints ([#26858](https://github.com/Azure/azure-sdk-for-net/issues/26858))
- [ ] [Text Analytics] Add Missing Bespoke Methods ([#28067](https://github.com/Azure/azure-sdk-for-net/issues/28067))
- [ ] [Text Analytics] Updates/Renames for Custom Text and Language ([#28213](https://github.com/Azure/azure-sdk-for-net/issues/28213))
- [ ] [Text Analytics] Support Cancellation of an Analyze Job ([#28116](https://github.com/Azure/azure-sdk-for-net/issues/28116))

# Release and Documentation

- [ ] [Text Analytics] Samples Enhancements ([#27608](https://github.com/Azure/azure-sdk-for-net/issues/27608))
- [ ] [Text Analytics] Add a sample for setting model version ([#25898](https://github.com/Azure/azure-sdk-for-net/issues/25898))
- [ ] Perform any needed release of the Text Analytics package to NuGet for features in the previous milestone

**Comment by maririos** [comment]
Package released https://www.nuget.org/packages/Azure.AI.TextAnalytics/5.2.0-beta.3
