### ISSUE TITLE
Archboard feedback for CLU 1.0 GA SDK

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29331]
- [x] Just show differences in asynchronous samples.
- [x] Don't use `continue` to skip and instead nest the `foreach` in an `if`.
- [x] See if the service is removing the "status" and "jobId" from the final output. (#29347)
- [x] Show a `Console.WriteLine` between getting an LRO and waiting on it.
- [x] Put sample parameters on separate parameters for `WaitUntil.Completed` calls.
- [x] Use WaitUntil.Completed and just use separate LROs for tests.
- [x] Update autorest for the feature branch (GA blocker).
- [x] `ConversationAuthoringClient`
- [x] Open an issue with comments here: https://apiview.dev/Assemblies/Review/20a58d7611e845939ebfd25707b16b88?revisionId=b218fb7529c54356a11d99e7e1daa4f5&doc=False#06f51472b6894935a0d0c153094ad53e (#29332)
- [x] Mention Language Studio in README with URL
- [x] Open issue on LRO stuff and include a breakdown of what LROs we have and which should return payloads (inference and authoring). (#29332)
- [x] Remaining feedback in https://apiview.dev/Assemblies/Review/20a58d7611e845939ebfd25707b16b88

Service:
- [x] How big do we expect export sizes? Might need another pattern.
- [x] Talk to service about updating their readme.md with CLU transforms, and about the 200/202 pattern for LROs.

APIView:
- [x] Need horizontal slider (Azure/azure-sdk-tools#3452)

**Comment by heaths** [comment]
> See if the service is removing the "status" and "jobId" from the final output.

This is odd. For [_Sample5_ImportProject.cs](), the `ImportProject` and `Train` LROs are working as expected based on the [session file](), but the `DeployProject` has an extra `GET` and I can't tell where it's coming from. Specifically, the initial LRO request indeed returns a 202 with an `Operation-Location` to a status monitor:

```json
      "StatusCode": 202,
      "ResponseHeaders": {
        "Access-Control-Expose-Headers": "*",
        "apim-request-id": "3d75422d-f5fe-4bcd-8cdc-c1b240e63a78",
        "Content-Length": "0",
        "Date": "Wed, 15 Jun 2022 01:02:17 GMT",
        "operation-location": "https://languagesdkresource.cognitiveservices.azure.com/language/authoring/analyze-conversations/projects/net-conv-367666463/deployments/production/jobs/ff2585da-967b-41dc-8f05-0a854689e260_637908480000000000?api-version=2022-05-01",
        "request-id": "3d75422d-f5fe-4bcd-8cdc-c1b240e63a78",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
        "X-Content-Type-Options": "nosniff",
        "x-envoy-upstream-service-time": "101"
      },
      "ResponseBody": null
```
The next several requests are what you'd expect - `status` is `running` - until the final status update:
```json
    {
      "RequestUri": "https://languagesdkresource.cognitiveservices.azure.com/language/authoring/analyze-conversations/projects/net-conv-367666463/deployments/production/jobs/ff2585da-967b-41dc-8f05-0a854689e260_637908480000000000?api-version=2022-05-01",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Ocp-Apim-Subscription-Key": "Sanitized",
        "User-Agent": "azsdk-net-AI.Language.Conversations/1.0.0-alpha.20220614.1 (.NET 6.0.5; Microsoft Windows 10.0.22000)",
        "x-ms-client-request-id": "ccc3e9c28c3c019344e0e2ad20829ff8",
        "x-ms-return-client-request-id": "true"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Access-Control-Expose-Headers": "*",
        "apim-request-id": "eb1b0550-ca5f-4a97-a177-169f5fdaaad4",
        "Content-Length": "218",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Wed, 15 Jun 2022 01:02:22 GMT",
        "request-id": "eb1b0550-ca5f-4a97-a177-169f5fdaaad4",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
        "X-Content-Type-Options": "nosniff",
        "x-envoy-upstream-service-time": "24"
      },
      "ResponseBody": {
        "jobId": "ff2585da-967b-41dc-8f05-0a854689e260_637908480000000000",
        "createdDateTime": "2022-06-15T01:02:17Z",
        "lastUpdatedDateTime": "2022-06-15T01:02:22Z",
        "expirationDateTime": "2022-06-22T01:02:17Z",
        "status": "succeeded"
      }
    },
```
But then immediately afterward, there's this extra GET which is what the `Operation<BinaryData>.Value` ultimately contains:
```json
    {
      "RequestUri": "https://languagesdkresource.cognitiveservices.azure.com/language/authoring/analyze-conversations/projects/net-conv-367666463/deployments/production?api-version=2022-05-01",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Ocp-Apim-Subscription-Key": "Sanitized",
        "User-Agent": "azsdk-net-AI.Language.Conversations/1.0.0-alpha.20220614.1 (.NET 6.0.5; Microsoft Windows 10.0.22000)",
        "x-ms-client-request-id": "8c11e8cce5e682c8638a22cdb3087be4",
        "x-ms-return-client-request-id": "true"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Access-Control-Expose-Headers": "*",
        "apim-request-id": "35de4d51-fcec-4df0-82ca-c06206d6f36f",
        "Content-Length": "281",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Wed, 15 Jun 2022 01:02:23 GMT",
        "request-id": "35de4d51-fcec-4df0-82ca-c06206d6f36f",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
        "X-Content-Type-Options": "nosniff",
        "x-envoy-upstream-service-time": "22"
      },
      "ResponseBody": {
        "deploymentName": "production",
        "modelId": "Sample5-20220615T010216-aeac9f0032944941b024163bc3ebff89",
        "lastTrainedDateTime": "2022-06-15T01:02:16.6869195Z",
        "lastDeployedDateTime": "2022-06-15T01:02:22Z",
        "deploymentExpirationDate": "2023-10-28",
        "modelTrainingConfigVersion": "2022-05-01"
      }
    }
```
I can't tell from where this comes? Why is the LRO querying the actual resource? The generated LRO implementation uses `OperationFinalStateVia.Location` just like the other aforementioned LROs:
```C#
using HttpMessage message = CreateDeployProjectRequest(projectName, deploymentName, content, context);
return LowLevelOperationHelpers.ProcessMessage(_pipeline, message, ClientDiagnostics, "ConversationAnalysisProjectsClient.DeployProject", OperationFinalStateVia.Location, context, waitUntil);
```

@annelo-msft @AlexanderSher @chunyu3 ?
/cc @kristapratico @mshaban-msft @tg-msft @johanste

**Comment by heaths** [comment]
Had issues with transforming away explicit pageable parameters. Opened Azure/autorest#4565 and Azure/autorest#4566 to track and ended up with a single transform:

```yaml
directive:
- from: swagger-document
  where: $.paths.*.*
  transform: |
    var paramRefs = [
        "common.json#/parameters/TopParameter",
        "common.json#/parameters/SkipParameter",
        "common.json#/parameters/MaxPageSizeParameter"
    ];
    if (/ConversationalAnalysisAuthoring_((List(Projects|Deployments|TrainedModels|TrainingJobs|TrainingConfigVersions))|Get(ModelEvaluationResults|SupportedLanguages|SupportedPrebuiltEntities))/.test($.operationId)) {
        $.parameters = $.parameters.filter(param => !paramRefs.includes(param["$ref"]));
    }
```

Not pretty, but it works. Also had to use `$.paths.*.*` instead of `$.paths..` as shown in the Azure/autorest repo in several places because I got an error without the asterisks:

```
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.23.5->4.23.5)
error   | directive/error | Error occured when running directive: Error: Parse error on line 1:
$.paths..
---------^
Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', '[', got '1'
```
