### ISSUE TITLE
Preview Release Azure.Monitor.Ingestion Checklist

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/azure-sdk-for-net#29535]
- [x] https://github.com/Azure/azure-sdk-for-net/issues/29477
- [x] https://github.com/Azure/azure-sdk-tools/issues/3483
- [x] https://github.com/Azure/azure-sdk-for-net/issues/29710
- [x] https://github.com/Azure/azure-sdk-for-net/issues/29711
- [x] Add Changelog
- [x] Add Readme
- [x] Add Samples
- [x] Ship library - Preview August, GA September
- [x] Update testing for batching

**Comment by nisha-bhatia** [comment]
Shipped: https://www.nuget.org/packages/Azure.Monitor.Ingestion/1.0.0-beta.2
