### ISSUE TITLE
[Azure.Monitor.Ingestion] Preview 2 Checklist

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/azure-sdk-for-net#30694]
2nd Preview Release - mid September
GA date - Sept 29, 22

- [ ] https://github.com/Azure/azure-sdk-for-net/issues/30693
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/30691
- [ ] add perf tests
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4103
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/30913
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/31074#discussion_r978010041
