### ISSUE TITLE
[Azure.Monitor.Ingestion] GA Checklist

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/azure-sdk-for-net#31758]
GA scheduled for November

- [ ] https://github.com/Azure/azure-sdk-for-net/issues/31008
- [x] https://github.com/Azure/azure-sdk-for-net/issues/31730
- [x] https://github.com/Azure/azure-sdk-for-net/issues/31259
- [x] https://github.com/Azure/azure-sdk-for-net/issues/31767
- [x] https://github.com/Azure/azure-sdk-for-net/issues/31796
- [x] https://github.com/Azure/azure-sdk-for-net/issues/32311
- [x] Perf tests
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/32715
- [x] https://github.com/Azure/azure-sdk-for-net/issues/32716
- [x] https://github.com/Azure/azure-sdk-for-net/issues/33135

Post GA
- Optional: https://github.com/Azure/azure-sdk-for-net/issues/33136
- Optional: https://github.com/Azure/azure-sdk-for-net/issues/33167
