### ISSUE TITLE
[Mgmt Plane][.NET] Unblock Track 1 to Track 2 migration 

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-for-net#34666]
### Tasks to unblock Track 1 to Track 2
- [ ] [Mgmt Plane][.NET] fill in the gaps between Track 1 and Track 2
- [ ] [Mgmt Plane][.NET] feature enhancement to unblock internal service migration - Model Factory
- [ ] [Mgmt Plane][.NET] feature enhancement to unblock internal service migration - Extract extension method as interface for mock test
- [ ] [Mgmt Plane][.NET] feature enhancement to unblock internal service migration - Rehydration support
- [ ] [[Mgmt Plane][.NET] Improve the migration experience for customers moving from Track 1 to Track 2](https://github.com/Azure/azure-sdk-for-net/issues/34668) 
- [ ] [[Mgmt Plane][.NET][Supportability] Continuously support internal/external user migrating to Track 2](https://github.com/Azure/azure-sdk-for-net/issues/34695)
