### ISSUE TITLE
Remove deprecated package sources

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#37660]
From <https://azure.github.io/azure-sdk/releases/deprecated/index.html#net>, remove packages' sources including build definitions as needed to avoid scanning alerts e.g., Component Governance, as well as unnecessary build time.

Do so using a PR for each service directory to make it easy to revert should we ever have to service a deprecated package (unlikely).

```[tasklist]
### Tasks
- [x] sdk/applicationinsights (Microsoft.Azure.ApplicationInsights.Query)
- [x] sdk/attestation (Microsoft.Azure.Attestation)
- [x] sdk/containerregistry (Microsoft.Azure.ContainerRegistry)
- [x] sdk/eventgrid (Microsoft.Azure.EventGrid)
- [x] sdk/eventhub (Microsoft.Azure.EventHubs, Microsoft.Azure.EventHubs.Processor)
- [x] sdk/graphrbac (Microsoft.Azure.Graph.RBAC)
- [x] sdk/hybriddatamanager (Azure.ResourceManager.HybridData)
- [x] sdk/keyvault (Microsoft.Azure.KeyVault, Microsoft.Azure.KeyVault.Core, Microsoft.Azure.KeyVault.Cryptography, Microsoft.Azure.KeyVault.Extensions, Microsoft.Azure.KeyVault.WebKey)
- [x] sdk/operationalinsights (Microsoft.Azure.OperationalInsights)
- [x] sdk/purview (Azure.Analytics.Purview.Share)
- [x] sdk/search (Microsoft.Azure.Search)
- [x] sdk/servicebus (Microsoft.Azure.ServiceBus)
- [x] sdk/storsimple8000series (Microsoft.Azure.Management.StorSimple8000Series)
- [x] sdk/trafficmanager (Microsoft.Azure.Management.TrafficManager)
- [x] sdk/websites (Microsoft.Azure.Management.WebSites)
```

You can use https://gist.github.com/heaths/587f0ed4f928fb5bd539c4680a793013 to discover deprecated Azure SDK for .NET packages.

**Comment by ArthurMa1978** [comment]
@heaths what's the common pattern of deprecation? Remove directly or move to another branch / repo?

**Comment by heaths** [comment]
@ArthurMa1978 remove entirely. There's no reason to keep it. It's always in git and reachable from `main`. Tagged sources (we tag when we release) are also reachable via their tag. Nothing is git is ever truly gone if reachable from a named object e.g., branches or tags.
