### ISSUE TITLE
Postgres

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#41980]
Add / update Postgress to support all of the customization shown here

- https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Azure/Bicep/AzureBicepPostgresResource.cs
- https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Azure/Bicep/postgres.bicep
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42508
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42509
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42510
```

**Comment by JoshLove-msft** [comment]
Added in https://github.com/Azure/azure-sdk-for-net/pull/42384
