### ISSUE TITLE
CDK / Aspire (P5) priorities.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-net#42348]
This is an overarching tracking issue for CDK API availability required for Aspire integration:

|Component|Priority|CDK API available|Aspire integration done|Polish pass|
|:----|:----|:----|:----|:----|
|[Storage](https://github.com/Azure/azure-sdk-for-net/issues/41986)|High|Available|Done|Due 3/8|
|[SQL Server](https://github.com/Azure/azure-sdk-for-net/issues/41985)|High|Available|Done|Due 3/8|
|[KeyVault](https://github.com/Azure/azure-sdk-for-net/issues/42349)|High|Available|Done|Due 3/8|
|[Redis](https://github.com/Azure/azure-sdk-for-net/issues/41981)|High|Available|Done|Due 3/8|
|[Postgres](https://github.com/Azure/azure-sdk-for-net/issues/41980)|High|Available|Done|Due 3/8|
|[Cosmos](https://github.com/Azure/azure-sdk-for-net/issues/41978)|High|Available|Done|Due 3/8|
|[ServiceBus](https://github.com/Azure/azure-sdk-for-net/issues/41984)|High|Available|Done|Due 3/15|
|AppConfig|Medium|Available|Done|Due 3/8|
|Open AI|Medium|Available|Done|Due 3/15|
|Azure Search|Medium|Available|Done|Due 3/15|
|SignalR|Medium|Available|Done|Due 3/15|
|Cosmos (Mongo)|Low|Available|Not started (target TBD)|Due 3/20|
|Azure DB for MySql|Low|Not started (target TBD)|Not started (target TBD)|Due 3/20|
|AppInsights|Next!|Available|In Review|TBA|
|Operational Insights|Next!|Available|In Review|TBA|
|Managed Identities|Available|Not started|Not started|TBA|
|Container Registries|Next!|Not started|Not started|TBA|
|Log Analytics Workspaces|Next!|Not started|Not started|TBA|
|Container App Managed Environments|Next!|Not started|Not started|TBA|
|Container Apps|In progress|Not started|Not started|TBA|
|Container Apps (Dapr)|Next!|Not started|Not started|TBA|

The goal is to deliver these CDK APIs sequentially so that we can get the Aspire integration going ASAP and frontload as much as possible in the Aspire P5 cycle.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/41986
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/41985
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/41981
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/41980
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/41978
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/41984
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42349
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42623
- [x] https://github.com/Azure/azure-sdk-for-net/issues/42574
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42572
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42573
- [x] EventHubs for CDK
- [ ] EventHubs with Kafka for CDK
- [ ] Cosmos with Mongo for CDK
- [ ] Azure Database for MySQL for CDK
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42402
```
