### ISSUE TITLE
[Core/ClientModel] Unbranded client support

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#42780]
# Expected outcomes

- The initial unbranded feature set needed for OpenAI is supported.
- Additional OpenAI features can be scheduled/implemented as they are requested.
- Client Model supports key scenarios for unbranded client development and parity with Azure Core.  

```[tasklist]
## Work needed _(estimate)_
- [ ] [Pipeline operation name (#42652)](https://github.com/Azure/azure-sdk-for-net/issues/42652) _(tiny)_
- [ ] [Logging policy (#42648)](https://github.com/Azure/azure-sdk-for-net/issues/42648) _(small)_
- [ ] [Open telemetry (#42115)](https://github.com/Azure/azure-sdk-for-net/issues/42115) _(medium)_
- [ ] [Multipart form data (#42105)](https://github.com/Azure/azure-sdk-for-net/issues/42105) _(medium)_
- [ ] [SSE Analysis (#42284)](https://github.com/Azure/azure-sdk-for-net/issues/42284) _(medium)_
```

### Estimate scale

- Tiny: 1-2 days
- Small: 3-5 days
- Medium: 1-2 weeks
- Large: 3-4 weeks
- XL:  More than 4 weeks

**Comment by jsquire** [comment]
Decided to change the approach for planning a bit.
