### ISSUE TITLE
//Get the Collator for US English and set its strength to PRIMARY  Collator usCollator = Collator.ec

### ISSUE THREAD

**Issue by Azile89** [Azure/azure-sdk-for-net#45100]
### Type of issue

Missing information

### Description

[//Get the Collator for US English and set its strength to PRIMARY  Collator usCollator = [Collator.ecEnter](url) feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.ai.vision.face.glassestype.swimminggoggles?view=azure-dotnet-preview

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.Vision.Face/GlassesType.xml

### Document Version Independent Id

1f703ca3-8fbd-6ab1-509b-81dbbd48f8ba

### Article author

@azure-sdk

### Metadata

* ID: f7792bea-e19a-4ebf-0f7b-cb21971d01da 
* Service: **azure**
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45093
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45080
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45084
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/45101
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/44804
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45096
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45078
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/43529
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/45089
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/44321
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45102
- [x] Triangle
```

**Comment by Azile89** [comment]
> 

> `[[[[`Elizamrse@gmail.com```Elizamybackyardcustoms@outlook.comexample]()](`url`)`com`](`url`)**403error301**](404pointto [`[`√^^)``](approve)`](url)
