### ISSUE TITLE
Expose `RequestOptions` for methods causing noisy logs/tracing

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#45297]
Replacing the original issue https://github.com/Azure/azure-sdk-for-net/issues/25626

The upcoming `Azure.RequestOptions` gives us the chance to expose [`ErrorOptions`](https://docs.microsoft.com/en-us/dotnet/api/azure.erroroptions?view=azure-dotnet) from our convenience methods.  We're not planning to do this everywhere, but there have been a handful of cases where the noise of an expected exception degraded the observability/diagnosability experience for customers.  This was discussed in detail in the ArchBoard meetings at https://github.com/Azure/azure-sdk/issues/3391.  This work item tracks enabling the first set of experiences for HLC libraries.

#### Foundational
- [x] Add `RequestOptions` - https://github.com/Azure/autorest.csharp/issues/1666
- [x] Support `RequestOptions` via the AutoRest's HLC generator - https://github.com/Azure/autorest.csharp/issues/1734

#### Use internally for both sync/async overloads:
- [ ] (Azure.Storage.Blobs) Blob Download - https://github.com/Azure/azure-sdk-for-net/issues/9934
- [x] (Azure.Storage.Blobs) Blob Exists - https://github.com/Azure/azure-sdk-for-net/issues/18592

#### Expose publicly both sync/async overloads:
- [ ] (Microsoft.Azure.WebJobs.Extensions.Storage) Receipt Manager - https://github.com/Azure/azure-sdk-for-net/issues/21511

#### Could either expose publicly or add an `If(Not)Exists` method to use internally for both sync/async overloads:
- [ ] (Azure.Search.Documents) Get Document - https://github.com/Azure/azure-sdk-for-net/issues/17445
- [ ] (Azure.Security.KeyVault.*) Delete - https://github.com/Azure/azure-sdk-for-net/issues/25125
- [x] (Azure.Data.Tables) CreateIfNotExists, CreateTableIfNotExists, GetEntitiy - https://github.com/Azure/azure-sdk-for-net/issues/16251
- [ ] (Azure.Data.AppConfiguration) Create - https://github.com/Azure/azure-sdk-for-net/issues/14802#issuecomment-996976716
