### ISSUE TITLE
[Epic] Create Azure plugin based on MTG

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-for-net#45615]
### Library name

N/A

### Please describe the feature.

With [MGC](https://github.com/microsoft/typespec/tree/main/packages/http-client-csharp/generator) in place, we can start to implement a new Azure plugin to replace [autorest.csharp](https://github.com/Azure/autorest.csharp)

- [ ] https://github.com/Azure/azure-sdk-for-net/issues/45616
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/45619
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/45620

**Comment by live1206** [comment]
close this since the skeleton is set up.
