### ISSUE TITLE
https://github.com/ceo-roblox-jun/azure-sdk-for-net.git

### ISSUE THREAD

**Issue by ceo-roblox-jun** [Azure/azure-sdk-for-net#45759]
### Type of issue

Missing information

### Description

https://github.com/ceo-roblox-jun/azure-sdk-for-net.git# retrieve cert config
$cert = Get-VstsClientCertificate
Write-Host $cert

# get project http client (the client will have proxy hook up by default)
$projectHttpClient = Get-VstsVssHttpClient -TypeName Microsoft.TeamFoundation.Core.WebApi.ProjectHttpClient -OMDirectory "<Directory that contains required .dlls>"

# print out all team projects
$projectHttpClient.GetProjects().ResultMicrosoft.TeamFoundation.Core.WebApi.ProjectHttpClientfunction Get-ClientCertificate {
    [CmdletBinding()]
    param()

    # Return a new X509Certificate2 object to the client certificate
    return New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Certificate2
}// MyCertExampleTask.ts
import tl = require('azure-pipelines-task-lib/task');
import api = require('vso-node-api');
import VsoBaseInterfaces = require('vso-node-api/interfaces/common/VsoBaseInterfaces');

async function run() {

    // get cert config
    let cert = tl.getHttpCertConfiguration();

    // TFS server url
    let serverUrl = "https://mycompanytfs.com/tfs";

    // Personal access token
    let token = "<YOUR_TOKEN_HERE>";
    let authHandler = api.getPersonalAccessTokenHandler(token);

    // Options for VSTS-Node-Api, 
    // this is not required if you want to send http request to the same TFS
    // instance the agent currently connect to.
    // VSTS-Node-Api will pick up certificate setting from azure-pipelines-task-lib automatically 
    let option: VsoBaseInterfaces.IRequestOptions = {
        cert: {
                caFile: "C:\\ca.pem",
                certFile: "C:\\client-cert.pem",
                keyFile: "C:\\client-cert-key.pem",
                passphrase: "test123",
            }
        };
    
    // Make a Rest call to VSTS/TFS
    let vsts: api.WebApi = new api.WebApi(serverUrl, authHandler, option);
    let connData: lim.ConnectionData = await vsts.connect();
    console.log('Hello ' + connData.authenticatedUser.providerDisplayName);

    // You should only use the retrieved certificate config to call the TFS instance your agent current connect to or any resource within your cooperation that accept those certificates.
}

run();MyCertExampleTask.tsVsoBaseInterfaces.IRequestOptionshttps://mycompanytfs.com/tfslim.ConnectionDataapi.WebApiexport interface CertConfiguration {
     caFile?: string;
     certFile?: string;
     keyFile?: string;
     certArchiveFile?: string;
     passphrase?: string;
 }

### Page URL

https://github.com/ceo-roblox-jun/azure-sdk-for-net.git

### Content source URL

https://github.com/ceo-roblox-jun/azure-sdk-for-net.git

### Document Version Independent Id

api.WebApi

### Article author

Damarcus Jones Sr 

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45742
- [ ] https://mycompanytfs.com/tfs
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45685
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45744
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/45671
```

**Comment by jsquire** [comment]
SPAM
