### ISSUE TITLE
[FEATURE REQ] Allow certificate rotation for Azure.Identity TokenCredentials

### ISSUE THREAD

**Issue by johnthcall** [Azure/azure-sdk-for-net#46373]
### Library name

Azure.Identity

### Please describe the feature.

TokenCredentials like ClientCertificateCredential only have constructors which accept a X509Certificate2, when the certificate rotates the only way to update it is to create a new credential and recreate all dependent clients. Azure.Identity should support rotation by exposing IX509Certificate2Provider constructors and X509Certificate2FromObjectProvider with a new method to update the certificate. 

These changes would allow consumers to create a X509Certificate2FromObjectProvider with their certificate, create a ClientCertificateCredential with it and then create all their SDK Client. When the certificate rotates they just need to update the certificate in X509Certificate2FromObjectProvider and then all downstream clients continue to work.

I would be happy to pick up this change.
```[tasklist]
### Tasks
- [ ] Make IX509Certificate2Provider public
- [ ] Make X509Certificate2FromObjectProvider public
- [ ] Make ClientCertificateCredential constructor IX509Certificate2Provider parameter public
- [ ] Add RotateCertificate method in X509Certificate2FromObjectProvider
```

**Comment by christothes** [comment]
Hi @johnthcall - Making the updates you outlined above wouldn't flow down to MSAL where the certificate provider is [only utilized to initialize the MSAL client](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/MsalConfidentialClient.cs#L125-L126). We'd probably need to push the ability to rotate certificates down to them first.

**Comment by christothes** [comment]
Closing as unplanned since this requires an update to MSAL. Please [file a feature request](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues) with them if you'd like to push this forward.
