### ISSUE TITLE
Tracking .NET 8 and 9 updates

### ISSUE THREAD

**Issue by m-redding** [Azure/azure-sdk-for-net#46639]
- [x] Add a .NET 8 target to RequiredTargetFrameworks and implicitly remove dependencies for packages built into the runtime in .NET 6 and beyond
    - Pull Request:
        - https://github.com/Azure/azure-sdk-for-net/pull/46637
    - Related:
        - https://github.com/Azure/azure-sdk-for-net/issues/38857
        - https://github.com/Azure/azure-sdk-for-net/issues/28477
        - https://github.com/Azure/azure-sdk-for-net/pull/28911
        - https://github.com/Azure/azure-sdk-for-net/issues/28492
        - https://github.com/Azure/azure-sdk-for-net/issues/28577
        - https://github.com/Azure/azure-sdk-for-net/issues/41628
- [x] Remove dependencies included in the runtime via central trimming mechanism
  - Pull Request:
    - https://github.com/Azure/azure-sdk-for-net/pull/46414 this was built into:
    - https://github.com/Azure/azure-sdk-for-net/pull/46637
- [x] Add .NET 9 to the test matrix and remove .NET 6
- [x] Update BCL packages to 8.x if possible
    - [x] Check PowerShell compatibility
    - [x] Check Functions compatibility - .NET 8 in-proc host?
    - Related:
        - https://github.com/Azure/azure-sdk-for-net/issues/46280
- [x]  Update global.json to .NET 9
- [x] https://github.com/Azure/azure-sdk-for-net/issues/45426
- [x] Modernize Azure.Core targets, net461 doesn't work with some of the 8.x dependencies. Should the net6.0 target be removed?
