### ISSUE TITLE
Tracking CI follow-ups from #47212

### ISSUE THREAD

**Issue by m-redding** [Azure/azure-sdk-for-net#47220]
There are some ci failures in https://github.com/Azure/azure-sdk-for-net/pull/47212

Since that PR is running over 1600 pipelines and has 480,000 loc changes, I would prefer not to address the ci failures in that PR. Instead, I am opening a tracking issue to make sure I follow up on all failed CIs.
- [x] net - eventgrid- ci
    - https://github.com/Azure/azure-sdk-for-net/pull/47217
- [x] net - storage - functions - ci 
    - https://github.com/Azure/azure-sdk-for-net/pull/47214
- [x] net - tables functions - ci
    - https://github.com/Azure/azure-sdk-for-net/pull/47226
