### ISSUE TITLE
Release KeyVault Track 2 Library Preview

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#5813]
Goal
 - [x] Create Secrets client library - Epic tracking the work #6050
 - [x] Create Keys client library - Epic tracking the work #6052

### Release
- [x] Validate package contents prior to publishing
- [x] Update docs with link to package
- [ ] Ensure docs are available

### Secrets
- [x] API Design proposal ready
- [x] API Design approved
- [x] Code complete
	- [x] Sync client
	- [x] Async client
- [x] Integration with Azure.Identity
	- [x] Dependency on azure.core-http
	- [x] New APIs added 
- [x] Test complete
	- [x] Infrastructure (ie. project ready)
	- [x] Tests for all APIs
		- [x] Live
			- [x] Nightly run
			- [x] Local
		- [x] Recorded
		- [x] Running in CI
- [x] Doc complete
	- [x] XML doc comments
	- [x] Readme following the guidelines
	- [x] Samples for HERO scenarios
	- [x] Document missing features vs Track 1

### Keys
- [x] API Design proposal ready
- [x] API Design approved
- [x] Code complete
	- [x] Sync client
	- [x] Async client
- [x] Integration with Azure.Identity
	- [x] Dependency on azure.core-http
	- [x] New APIs added 
- [x] Test complete
	- [x] Infrastructure (ie. project ready)
	- [x] Tests for all APIs
		- [x] Live
			- [x] Nightly run
			- [x] Local
		- [x] Recorded
		- [x] Running in CI
- [x] Doc complete
	- [x] XML doc comments
	- [x] Readme following the guidelines
	- [x] Samples for HERO scenarios
	- [x] Document missing features vs Track 1

**Comment by AlexGhiondea** [comment]
The docs are available on the github.io site.
