### ISSUE TITLE
Release Azure.Core Library Preview 3 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#5933]
### API Design ###
- [ ] Design approved

### Features ###
- [x] Support log redaction (#6156)
- [x] Long running operations - (#6158)
- [x] Batch operations - (#6157)
- [x] Azure.Core API Review - (#6170)
- [x] Distributed tracing for AMQP based protocols
- [x] Cosmos DB unification of the pipeline (#7097, #7099)
- [ ] Recorded tests improvements (#6905 #6903 #6889)
- [x] Response stream disposal improvement (#6841)
- [x] Wrapping transport layer exceptions (#6817)
- [x] Content size limit for logging policy (#6191)
- [x] Non-Nullable reference types annotations (#6938)

### Docs ###
- [x] Xml docs - Add xml doc to azure core (#6870)
