### ISSUE TITLE
Release Event Hubs Client Library Track Two Preview 1

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#6030]
# Summary

Azure Event Hubs is a highly scalable publish-subscribe service that can ingest millions of events per second and stream them into multiple applications.  To ensure that developers around the world have a first-class experience leveraging Azure Event Hubs in their applications, its SDK should provide an API that is intuitive and powerful, and which looks and feels consistent within the .NET ecosystem.

# Goal

Design, develop, and release a preview version of the Event Hub client library which can be used to gather feedback and help refine the design.

# Success Criteria

A preview of the Event Hubs client library which follows the [Azure SDK Design Guidelines](https://azuresdkspecs.z5.web.core.windows.net/DesignGuidelines.htm) as closely as possible, and which has been approved by the Azure Developer Platform architecture board has been made available for release.

# Scope

### Design

- [x] Design the API experience for the target scenarios ([#6109](https://github.com/azure/azure-sdk-for-net/issues/6109), [#6113](https://github.com/azure/azure-sdk-for-net/issues/6113), [#6112](https://github.com/azure/azure-sdk-for-net/issues/6112), [#6110](https://github.com/azure/azure-sdk-for-net/issues/6110))  

- [x] Create a prototype of the proposed API design for review ([#6117](https://github.com/azure/azure-sdk-for-net/issues/6117))  

- [x] Obtain approval for the proposed API design from the architecture board ([#6166](https://github.com/Azure/azure-sdk-for-net/issues/6166), [#6118](https://github.com/azure/azure-sdk-for-net/issues/6118))

### Plan

- [x] Identify gaps in the current implementation against Azure SDK Guidelines([#6104](https://github.com/azure/azure-sdk-for-net/issues/6104), [#6105](https://github.com/azure/azure-sdk-for-net/issues/6105), [#6016](https://github.com/azure/azure-sdk-for-net/issues/6106), [#6107](https://github.com/azure/azure-sdk-for-net/issues/6107), [#6108](https://github.com/azure/azure-sdk-for-net/issues/6108), [#6114](https://github.com/azure/azure-sdk-for-net/issues/6114))  

- [x] Decompose identified work items, and document them for implementation ([#6121](https://github.com/azure/azure-sdk-for-net/issues/6121))  

#### For Release

- [x] Prepare track one client library as the basis of implementation ([#6335](https://github.com/Azure/azure-sdk-for-net/issues/6335))  

- [x] Implement track one compatibility layer ([#6336](https://github.com/Azure/azure-sdk-for-net/issues/6336), [#6337](https://github.com/Azure/azure-sdk-for-net/issues/6337), [#6338](https://github.com/Azure/azure-sdk-for-net/issues/6338), [#6339](https://github.com/Azure/azure-sdk-for-net/issues/6339), [#6340](https://github.com/Azure/azure-sdk-for-net/issues/6340) [#6511](https://github.com/Azure/azure-sdk-for-net/issues/6511))

- [x] Tests for features and scenarios supported by the new API surface ([#6348](https://github.com/Azure/azure-sdk-for-net/issues/6348), [#6349](https://github.com/Azure/azure-sdk-for-net/issues/6349), [#6351](https://github.com/Azure/azure-sdk-for-net/issues/6351), [#6352](https://github.com/Azure/azure-sdk-for-net/issues/6352), [#6353](https://github.com/Azure/azure-sdk-for-net/issues/6353))

- [x] Prepare Documentation and Samples ([#6120](https://github.com/azure/azure-sdk-for-net/issues/6120), [#6354](https://github.com/Azure/azure-sdk-for-net/issues/6354), [#6355](https://github.com/Azure/azure-sdk-for-net/issues/6355), [#6356](https://github.com/Azure/azure-sdk-for-net/issues/6356))

**Comment by NatanaelLemos** [comment]
Hello friends, do this mean we'll have a release in June?

**Comment by AlexGhiondea** [comment]
@NatanaelLemos we are working towards having a preview release sometime in the summer.

**Comment by NatanaelLemos** [comment]
@AlexGhiondea awesome, thanks!

**Comment by jsquire** [comment]
### First Preview Release Information

- NuGet Package: [Azure.Messaging.EventHubs](https://www.nuget.org/packages/Azure.Messaging.EventHubs/)
- Release Notes:  [https://aka.ms/azure-sdk-preview1-net](https://aka.ms/azure-sdk-preview1-net)
