### ISSUE TITLE
Release Azure.Identity Library Preview

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#6043]
Goal:

Release the Azure.Identity library
Integrate this library in the other client libraries.

- [ ] Gap Analysis of MSAL 
- [ ] Provide Feedback to MSAL Team and schedule updates
- [ ] Finalize Azure.Identity footprint for SDK Preview
- [x] Azure.Core Updates
  - [x] TokenCredential ABC
  - [x] BearerTokenAuthenticationPolicy
- [ ] Azure.Identity
  - [ ] Classes
    - [x] AzureCredential
    - [x] ClientSecretCredential
    - [ ] ClientCertificateCredential
    - [ ] MSICredential
    - [x] TokenCredentialProvider
    - [x] EnvironmentCredentialProvider
    - [ ] MSICredentialProvider
    - [ ] Undecided: GlobalTokenCache?
  - [ ] Implementations
    - [x] ClientSecretCredential
    - [ ] ClientCertificateCredential
    - [ ] ManagedIdentityCredential
    - [ ] Undecided: User Credentials?
- [ ] Investigate other authentication schemes we need to support (user auth, auth from shared token cache)

**Comment by jianghaolu** [comment]
Will there be plans to read logged in user's credentials from Visual Studio or Azure CLI?

**Comment by joshfree** [comment]
Closing Preview 1 (July Preview) Epic
