### ISSUE TITLE
Update Keys client for KeyVault track 2 client library preview

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#6052]
This epic is consider to be done when the following are accomplished:
- [x] Key API design (management API only)
- [x] Key API review
- [x] Key client implementation
  - [x] Sync
  - [x] Async
- [x] Add test coverage
- [x] Add documentation

**Comment by maririos** [comment]
All work for keys is done. The release of the package is managed by epic #5813
