### ISSUE TITLE
Release KeyVault Track 2 Library Preview 3 for .NET

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#6054]
### API Design ###
- [ ] Certificates API
  - [x] Proposal ready
  - [ ] Design approved

### Features ###
- [ ] Support for Certificates API
  - [x] Challenge based auth
  - [ ] Code complete
    - [ ] Sync methods
    - [ ] Async methods
  - [ ] Testing complete
  - [ ] Support polling APIs for certs

### Docs ### 
- [ ] Samples
- [ ] ReadMe updates
- [ ] Change log
