### ISSUE TITLE
Release KeyVault Track 2 Library Preview 2 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#6675]
### API Design ###
- [x] Proposal ready
- [x] Design approved

### Features ###
- [x] Challenge based auth
  - [x] Code complete
  - [x] Testing complete
- [x] Crypto support for keys
  - [x] Crypto via the service
    - [x] Code complete
      - [x] Async methods
      - [x] Sync methods
    - [x] Testing complete

### Docs ###
- [x] Samples
- [x] Readme updates
