### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 2 for .NET

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#6752]
# Summary

Azure Event Hubs is a publish-subscribe service that can ingest millions of events per second and stream them into multiple applications.  To ensure that developers around the world have a first-class experience leveraging Azure Event Hubs in their applications, our goal is to create a client library that is developer-friendly, idiomatic to the .NET ecosystem, and as consistent across different languages and platforms as possible.   

The work items herein represent the tasks needed to produce the second preview of the "track two" Event Hubs client library.

# Goal

Design, develop, and release the second preview of the Event Hub client library, intended to allow developers to work with it and offer their feedback which we will use to help refine the design.

# Success Criteria

The second preview of the Event Hubs client library which follows the [Azure SDK Design Guidelines](https://azuresdkspecs.z5.web.core.windows.net/DesignGuidelines.htm) as closely as possible, and which has been approved by the Azure Developer Platform architecture board has been made available for release.

# Scope

### Design and Plan

- [x] Decompose identified work items, and document them for implementation

- [x] Perform analysis and design of the scope for the second preview, including determining target scenarios ([#6777](https://github.com/Azure/azure-sdk-for-net/issues/6777))

- [x] Design and document the API experience for the target scenarios ([#6778](https://github.com/Azure/azure-sdk-for-net/issues/6778))

#### General

- [x] Ensure that partition properties in all uses are based on an `int` type for offset.  ([#6779](https://github.com/Azure/azure-sdk-for-net/issues/6779))

- [x] Convert `DateTime` to `DateTimeOffset` for public members ([#6780](https://github.com/Azure/azure-sdk-for-net/issues/6780))  

- [x] Introduce an exception hierarchy ([#6782](https://github.com/Azure/azure-sdk-for-net/issues/6782))  

- [x] Create infrastructure for retry policy changes ([#6784](https://github.com/Azure/azure-sdk-for-net/issues/6784))  

- [x] Include test coverage for diagnostics and logging ([6793](https://github.com/Azure/azure-sdk-for-net/issues/6793))  

#### Event Hub Client

- [x] Adopt the new retry policy structures ([#6785](https://github.com/Azure/azure-sdk-for-net/issues/6785))  

#### Event Hub Consumer

- [x] Adopt the new retry policy structures ([#6787](https://github.com/Azure/azure-sdk-for-net/issues/6787))  

- [x] Implement the updated streaming receive feature  ([#6788](https://github.com/Azure/azure-sdk-for-net/issues/6788))

#### Event Hub Producer

- [x] Adopt the new retry policy structures ([#6786](https://github.com/Azure/azure-sdk-for-net/issues/6786))  

- [x] Implement the updated `EventBatch` infrastructure  ([#6791](https://github.com/Azure/azure-sdk-for-net/issues/6791))  

- [x] Allow publishing an `EventBatch` ([#6792](https://github.com/Azure/azure-sdk-for-net/issues/6792))  

### Document

- [x] Enhance Documentation ([#6795](https://github.com/Azure/azure-sdk-for-net/issues/6795))

- [x] Prepare Samples ([#6797](https://github.com/Azure/azure-sdk-for-net/issues/6797))

**Comment by NickDarvey** [comment]
Wait, is the Event Hub client library being rewritten _again_? Is there anywhere I can read more about this?

> Design and document the API experience for the target scenarios

Can unit testing be one of these target scenarios? The previous library required wrapping a bunch of classes. (See [the discussion](https://github.com/Azure/azure-event-hubs-dotnet/issues/24) in previous library's issues, and what I [had](https://github.com/NickDarvey/ServiceFabric.EventHubs/blob/master/ServiceFabric.EventHubs/TestableEventHubClient.cs) [to](https://github.com/NickDarvey/ServiceFabric.EventHubs/blob/master/ServiceFabric.EventHubs/TestablePartitionReceiver.cs) [do](https://github.com/NickDarvey/ServiceFabric.EventHubs/blob/master/ServiceFabric.EventHubs/TestableSystemPropertiesCollection.cs).)

**Comment by jsquire** [comment]
Hi Nick,

Thank you for taking the time to share your thoughts.  I can't speak to the development history of the Event Hubs client, but we are in the process of building a new Event Hubs client library.  The new client library will exist in a new package and namespace; our goal is that there is no disruption to existing library users, allowing the choice of whether to adopt the new library or not and, if so, control over the timing.

With respect to the larger context, until recently, the team that owned an Azure service also had responsibility of creating the associated client libraries for their service.  While this was great for ensuring that client libraries were well-aligned to the service, it often meant that client libraries were inconsistent with those for other Azure services.  Likewise, the client libraries could also often be inconsistent for the same service across different languages and/or feel uncomfortable because they didn't conform to the expected language idioms.

Microsoft recently created a new team responsible for the developer experience for all of the Azure services, the Azure Developer Platform team.  Our goal is to unify the experience for developers, providing an API that is consistent, discoverable, and idiomatic to its language and platform.  I don't know of an official landing page that introduces our team, but I can suggest following the [Azure SDK Team](https://twitter.com/AzureSdk) account on Twitter if you're interested in keeping up with announcements or conversing with the team.  Maggie or Alex (copied) may have additional references for you.

For information specific to the work that we're doing for Event Hubs, you may want to look at:

- [Event Hubs client design proposals](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs/design)
- [Azure SDK Design Guidelines for .NET](https://azuresdkspecs.z5.web.core.windows.net/DotNetSpec.html)

Testability is one of the areas that we're focused on; ensuring that clients are mockable by developers and can be tested without a reliance on Azure resources is important to us.  We will be releasing a preview of the new Event Hubs client in the near future and would very much welcome your feedback on how we're doing in that respect.   One final thing that I'd like to call attention to is that we are an open source project and welcome any feedback or contributions that you'd like to provide.  I will ask that you'd be kind enough to open a dedicated issue for further feedback, as this is intended to be a work tracking item and I want to be sure that your thoughts are more widely visible so that we can triage and route them appropriately.

//cc: @AlexGhiondea, @maggiepint
