### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 2 for .NET

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#6933]
- [x] Spec for Distributed Tracing Produced @johanste 
- [x] Distributed Tracing Plugin / Context updated for Open Telemetry for .NET @pakrym 
- [x] Tracing Context propagated through each Track 2 HTTP-based Library @pakrym 
   - [x] AppConfiguration
   - [x] Azure.Core
   - [x] Azure.Identity
   - [x] KeyVault
   - [x] Storage
- [x] OpenTelemetry preview package pushed to NuGet.org 8/2 @lmolkova 
- [x] Open Telemetry Library for .NET Standard Produced @tarekgh @ericstj @noahfalk

**Related**
- Preview 2 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/6933
- Preview 3 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7069
- Preview 4 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7070

**Comment by joshfree** [comment]
Closing Epic tracking Distributed Tracing Preview 2 feature work
