### ISSUE TITLE
Release Storage Track 2 Library Preview 3 For .Net

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#6952]
*=Work owned by _xstore_ team

#### New Service Features
- [x] * CPK #6999 (must-have for preview 3)
- [x] * File SMB properties REST parity #7001 (must-have for preview 3)
- [x] * Rehydrate Priority #6998
- [x] * Set Tier

#### Feature work
- [x] * Parallel upload and download #6274
- [x] Make UriBuilders public #6885
- [x] Add convenience for File Upload #6893
- [x] Unified Swagger #6900

#### Fit and finish
- [x] Fix response buffering for downloads #6891

**Comment by kurtzeborn** [comment]
Preview 3 has shipped!
