### ISSUE TITLE
Release Service Bus Track 2 Library Preview 1 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#6993]
This is a parent issue tracking the work planned for Service Bus to release the first preview in March following the [C# .Net Azure SDK guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html) 
Code complete date: March 6th, 2020

API design
- [x] Revisit the client structure i.e the various entry points in the package based on the .Net guidelines

Features
- [x] Support Azure Identity like we did in Event Hubs
- [x] Support retry configurability on clients like we did in Event Hubs
- [x] Support Web sockets & proxy like we did in Event Hubs
- [x] Send message to Queue
- [x] Receive and settle message from Queue
- [x] Receive and settle message from seesion enabled Queue

**Comment by Petermarcu** [comment]
@AlexGhiondea is this one closable?

**Comment by AlexGhiondea** [comment]
@petermarcu this is to track the upcoming work.

**Comment by ramya-rao-a** [comment]
The issue description has been updated with latest details on the expectation around the first preview for the .Net library

**Comment by ramya-rao-a** [comment]
@JoshLove-msft, @ShivangiReja Let's close this issue with a link to the nuget package no wthat the first preview is out

**Comment by JoshLove-msft** [comment]
https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.0.0-preview.1
