### ISSUE TITLE
Release Azure.Identity Library Preview 3 for .NET

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#7065]
**API Design**
- [ ] **Preview 3** Arch Board review of Preview 2 Credential Types
   - [ ] Proposal Ready
   - [ ] Design approved
- [ ] **Preview 3** SharedTokenCacheCredential APIs reviewed and approved by Azure SDK Core Arch Board
   - [ ] Proposal Ready
   - [ ] Design approved
- [ ] **Preview 3** Finalize MSAL dependency strategy with Arch Board
   - [ ] Proposal Ready
   - [ ] Design approved
- [ ] **Preview 3** Review Exception Patterns across languages
- [ ] **Preview 3** Review Authority Host Configuration and ensure consistency across Languages

**Feature Work**
- [ ] **Preview 3** Provide Feedback & File Issues for MSAL Team (ex: Java) and schedule updates
- [ ] **Preview 3** Provide Single Sign-On (SSO) Authentication Support with MSAL
   - [ ] Verify Shared Token Cache Design works with mainline scenarios (Visual Studio, Powershell, CLI)
- [ ] **Preview 3** _Stretch Goal_ Provide On-Behalf-of (OBO) authorization support  with MSAL

**Documentation**
- [ ] **Preview 3** Samples, Snippets, and Documentation completed for SSO Auth

**Related**
   - [ ] Preview 4 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7278
   - [ ] Preview 3 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7065
   - [ ] Preview 2 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6917
   - [ ] Preview 1 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6043
