### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 3 for .NET

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#7069]
**API Design**
- [x] **Preview 2** (HTTP) Spec for Distributed Tracing Produced @johanste 
   - [x] Spec Ready
   - [x] Spec approved by Azure SDK Arch Board
- [x] **Preview 3** (AMQP) Spec for Distributed Tracing Produced @johanste @lmolkova 
   - [x] Spec Ready - https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#file-minimal_instrumentation-md
   - [ ] Spec approved by Azure SDK Arch Board
- [ ] **Preview3** OpenTelemetry AMQP support designed @lmolkova 
   - [ ] Spec Ready
   - [ ] Spec approved by OpenTelemetry Maintainers
- [x] **Preview3** Distributed Tracing Plugin Package Name Standardized @johanste 

**Feature Work**
- [x] **Preview 3** OpenTelemetry is updated with AMQP Support
   - [x] OpenTelemetry AMQP support implemented
   - [x] OpenTelemetry Packages available for testing by Azure SDK team
   - [x] Azure SDK Distributed Tracing Plugin / Context tested with OpenTelemetry for each language
- [ ] **Preview 3** Tracing Context propagated through each Track 2 Library
   - [ ] KeyVault (Certificates) - @schaabs 
   - [x] EventHubs (amqp) - @pakrym 
   - [ ] EPH (amqp) - @pakrym 

**Documentation**
- [x] **Preview 3** Samples, Snippets, and Documentation completed for Distributed Tracing with Track 2 SDK Previews

**UX**
- N/A for Preview 3

**Related**
- Preview 2 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/6933
- Preview 3 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7069
- Preview 4 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7070
