### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 4 for .NET

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#7070]
**API Design**
- N/A for Preview 4

**Feature Work**
- [x] **Undone from Preview 3** Tracing Context propagated through each Track 2 Library
   - [x] KeyVault (Certificates)
   - [x] EPH (amqp)
- [x] **OpenTelemetry**
   - [x]  add Links support 
   - [x] ship a package

**Documentation**
- N/A for Preview 4

**CUT**
- [ ] **Preview 4** Before the UX study, audit to make sure tracing is consistent across each language
- [ ] **Preview 4** React to UX study feedback
- [ ] **Preview 4** UX study (validate theory that tracing support in Azure SDK is extremely useful for diagnosing reliability issues)

**Related** 
- Preview 2 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/6933
- Preview 3 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7069
- Preview 4 Tracing Epic for .NET: https://github.com/Azure/azure-sdk-for-net/issues/7070
