### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 3 for .Net

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#7141]
For general summary & goal, please see: [Release Event Hub Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442) 

The work items linked to this issue herein represent the tasks needed to produce the 3rd preview for the "track two" Event Hubs client library.

### API Design Review with the Board for Create using batch & Consume using Event Processor
- [ ] 🏃‍♀Proposal Ready
- [ ] 🏃‍♀Review scheduled
- [ ] Design approved
- [ ] Capture work items for any needed revisions

#### General
- [x] Decompose the AMQP transport layer scope into work items, and document them for implementation
- [x] Decompose the `EventProcessor` feature scope into work items, and document them for implementation
- [x] Follow-up on the need for Consumer Run time Metrics with the service team
- [x] Follow-up on system properties with the service team, to understand needed attributes and target use scenarios

#### Event Processor
- [x] Automatic load balancing ([#7377](https://github.com/Azure/azure-sdk-for-net/issues/7377))
- [x] Select a durable store for checkpoint and ownership information
- [x] 🏃  Implement a stand-alone package with the concrete partition manager
- [x]  Test coverage ([#7182](https://github.com/Azure/azure-sdk-for-net/issues/7182))

#### AMQP Transport Layer
- [x] Message conversion ([#7180](https://github.com/Azure/azure-sdk-for-net/issues/7180))
- [x] Foundation for connections and sessions ([#7187](https://github.com/Azure/azure-sdk-for-net/issues/7187))
- [x] AMQP Event Hub Client ([#7190](https://github.com/Azure/azure-sdk-for-net/issues/7190))

#### Consuming Events
- [x] Revisit System Properties and refactor([#7179](https://github.com/Azure/azure-sdk-for-net/issues/7179), [#7356](https://github.com/Azure/azure-sdk-for-net/issues/7356))
- [x] Resurrect runtime metrics, in draft form (_no associated issue_)

#### Diagnostics 
- [x] Implement distributed tracing via Diagnostics Activities and remove the embedded track one version.

#### General Improvements
- [x] Fix compilation issue under .NET Core 3 preview7 ([#7151](https://github.com/Azure/azure-sdk-for-net/issues/7151))
- [x] Improve asynchronous enumerator performance and efficiency ([#7094](https://github.com/Azure/azure-sdk-for-net/issues/7094))
- [x] Stabilize nightly test runs ([#7181](https://github.com/Azure/azure-sdk-for-net/issues/7181), [#7220](https://github.com/Azure/azure-sdk-for-net/issues/7220))
- [x] Adjust test metadata decorators to remove redundancy ([#7095](https://github.com/Azure/azure-sdk-for-net/issues/7095))

### Documentation
- [x] Reference documentation ([#7183](https://github.com/Azure/azure-sdk-for-net/issues/7183))
- [ ] 🏃‍♀ Samples ([#7185](https://github.com/Azure/azure-sdk-for-net/issues/7185))
- [x] Changelog ([#7185](https://github.com/Azure/azure-sdk-for-net/issues/7185))
