### ISSUE TITLE
Release KeyVault Track 2 Library Preview 4 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#7274]
### Features ###
- ~Add separate client for service crypto~
- [x] Crypto support for keys
  - ~Support multi-block crypto in Keys~
  - [ ] Crypto on the client (#7518)
    - [x] Code complete
      - [x] Async methods
      - [x] Sync methods
    - [x] Testing complete
      - ~Verify local operations on the server, and vice versa (#7725)~
- [x] Support for LRO for Certificates
- [x] Change to composition model for Certificate, Key, and Secret classes
- [x] Normalize types with other languages (names, structures)
- ~Improve test coverage~
  - ~Cleanup resources at the end of the test run (#7415)~
- [x] Support for Storage client side encryption
- ~Move all the Model types into a .Models namespace~
- [x] Reduce code duplication
  - [x] Unify argument validation (#7547)

### Docs ###
- [x] Samples
- [x] ReadMe updates
- [x] Change log
