### ISSUE TITLE
Release Azure.Identity Library Preview 4 for .NET

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#7278]
**API Design**
- [x] **Preview 4** Review Exception Patterns across languages (@schaabs)
- [x] **Preview 4** Review Authority Host Configuration and ensure consistency across Languages (@schaabs)

**Feature Work**
- [x] **Preview 4**  Authorization Code Flow support with MSAL https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
- [x] **Preview 4** Create a combination of Automated and Manual testing (postman, curl, etc documented steps)
   - [x] Define Positive/Negative/Stress SSO test cases (cross applications, cross browser tabs)

**Documentation**
- [x] N/A

**CUT**
- [x] **Preview 4** Design solution for publishing credentials to shared token cache for dev-time experience (@schaabs)
- [x] **Preview 4** Implement solution for publishing credentials to shared token cache
   - [x] Cross-Language-SDK testing to ensure the Shared Token Cache functions as expected (correct synchronization)

**Related**
   - [ ] Preview 4 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7278
   - [x] Preview 3 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7065
   - [x] Preview 2 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6917
   - [x] Preview 1 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6043

**Comment by joshfree** [comment]
Closing as Preview 4 (October Preview) has been release for Azure.Identity
