### ISSUE TITLE
Release Azure.Core Library Preview 4 for .NET

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7553]
# Distributed tracing

- [x] OpenTracing support for links https://github.com/Azure/azure-sdk-for-net/issues/7552
- [x] EPH instrumentation https://github.com/Azure/azure-sdk-for-net/issues/7554
- [x] Sample https://github.com/Azure/azure-sdk-for-net/issues/7566
- [ ] Extract activity https://github.com/Azure/azure-sdk-for-net/issues/7749

# Azure.Core proper
- [x] Azure.Core should wrap all transport layer exceptions https://github.com/Azure/azure-sdk-for-net/issues/6817
- [x] Azure.Core API review and address feedback  https://github.com/Azure/azure-sdk-for-net/issues/6170
- [x] Consider making Response<T> a class and having AsyncCollection/Operation inherit from it https://github.com/Azure/azure-sdk-for-net/issues/7520
- [x] Consider making the Message an ultimate exchange type for the pipeline https://github.com/Azure/azure-sdk-for-net/issues/7519
- [x] Design SyncCollection https://github.com/Azure/azure-sdk-for-net/issues/7039
- [x] AzureClientBuilderExtensions should not show in the root namespaces of clients https://github.com/Azure/azure-sdk-for-net/issues/7493
- [x] Disabling default policies (for batch) https://github.com/Azure/azure-sdk-for-net/issues/7521
- [x] Storage retry policy https://github.com/Azure/azure-sdk-for-net/issues/7558

# Logging
- [x] Log redaction support https://github.com/Azure/azure-sdk-for-net/issues/6156
- [x] Content size limit https://github.com/Azure/azure-sdk-for-net/issues/6191
- [ ] Finalize logging event source guidance https://github.com/Azure/azure-sdk-for-net/issues/7555
- [x] Console logger listener in azure.core https://github.com/Azure/azure-sdk-for-net/issues/7556
- [x] Verify logging E2E https://github.com/Azure/azure-sdk-for-net/issues/7557
- [x] Disable logging content by default add a flag https://github.com/Azure/azure-sdk-for-net/issues/7559
