### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 4 for .Net

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#7562]
For general summary & goal, please see: [Release Event Hub Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442) 

The work items linked to this issue herein represent the tasks needed to produce the 4th preview for the "track two" Event Hubs client library.

## API Design Review with the Board 
- [x] Create and send batch

#### AMQP Transport Layer
- [x] Foundation for Amqp links ([#7188](https://github.com/Azure/azure-sdk-for-net/issues/7188))
- [x] Amqp Event Hub Consumer ([#7192](https://github.com/Azure/azure-sdk-for-net/issues/7192))

#### Diagnostics 
- [x] Integrate logging via event source ([#7129](https://github.com/Azure/azure-sdk-for-net/issues/7129))

#### Miscellaneous
- [x] Investigate the issues reported in review of the preview 3 documentation and samples _(Issue needed)_

### Release & Documentation
- [x] Release packages to Nuget _(Issue needed)_
- [x] Reference documentation ([#7587](https://github.com/Azure/azure-sdk-for-net/issues/7587))
- [x] Changelog ([#7587](https://github.com/Azure/azure-sdk-for-net/issues/7587))
- [x] Samples ([#7588](https://github.com/Azure/azure-sdk-for-net/issues/7588))
