### ISSUE TITLE
Release AzConfig Track 2 Library Preview 4 for .NET

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#7573]
This is to track the work for Preview 4

### API Design ###
- [ ] Design approved
- [x] Design for ETags/Precondition headers (#5412, https://github.com/Azure/azure-sdk/issues/638)
- [x] Misc design issues (#5393)

### Features ###
- [x] Support for custom headers (#7124, #7441)
- [x] Support for HEAD request (HasChanged) (#7440)
- [x] Implement use of service version (#5368)
- [x] Sync-Token Header (#5380)
- [ ] Make Equals an object reference (#5475)
- [x] Apply design guidance from outcome of ETag discussion (#7757)
- [ ] Setting batch filter (#5389)
- [ ] Various cleanup items (#7084, #7130, #7732)
- [ ] .NET Provider support (#5408)

### Docs ###
- [ ] Samples 
  - [x] Lock/Unlock (#7402)
  - [ ] Read Revision History
  - [ ] Conditional Get/Set
- [ ] README
- [ ] Quickstarts

**Comment by annelo-msft** [comment]
Released & moved remaining to P5.
