### ISSUE TITLE
Release AzConfig Track 2 Library Preview 5 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#7904]
### API Design ###
- [x] Final arch board API design review
- [x] Cross-language, resolve consistency around 204/304 (don't throw on 304), and update general guidelines

### Features ###
- [ ] Endpoint + token constructor, pending service support of AAD (#7571)
       - Clarify whether we disable current HMAC signing
- [x] Resolve consistency around 204/304  (#7915)
- [x] Make Equals an object reference (#7906, #5475)
- [x] Setting batch filter (#5389)
- [x] Various cleanup items (#7084, #7130, #7732, #7861, #7248, #7244)
- [x] Complete provider integration (#5408)

### Docs ###
- [x] Samples (#7138)
  - [x] Read Revision History (#7402)
  - [x] Conditional Get/Set (#7402)
- [x] README (#7225)
- [x] Quickstarts
- [ ] Contributing (#7244)
- [x] Docstrings (#7224)
