### ISSUE TITLE
Release KeyVault Track 2 Library Preview 5 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#7905]
### Features ###

- [x] Remove IV, authentication data, and authentication tag (#8010)
- [x] API review complete and changes made as needed (#6078)
  - [x] Also changes from UX studies
  - [x] Change Delete* and RecoverDeleted* to LROs for KeyClient and SecretClient (#8123)
- [X] Add Event Source for diagnostic messages (#7648)
- [x] Testing complete
  - ~Migrate track 1 coverage (#6064)~

### Docs ###

- [X] Make sure all public API XML doc comments are present, checked
    - [x] Improve XML doc comments for Keys and Secrets clients (#6076)
- [X] Update samples
  - [X] Include more async examples, especially of async enumerables
- [X] Update READMEs
- [x] Update change log
  - [x] Certificates (few changes, but still releasing preview)
  - [x] Keys
  - [x] Secrets
