### ISSUE TITLE
Release Azure.Identity Library Preview 5 for .NET

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#7909]
**API Design**
- [x] N/A

**Feature Work**
- [ ] Fix remaining active issues (excludes Milestone=Backlog) https://github.com/Azure/azure-sdk-for-net/issues?q=is%3Aopen+is%3Aissue+label%3AAzure.Identity+no%3Amilestone

**Documentation**
- [x] N/A

**Related**
   - [x] Release Azure.Identity Track 2 (parent epic) Library https://github.com/Azure/azure-sdk/issues/536
   - [x] Preview 4 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7278
   - [x] Preview 3 for .NET https://github.com/Azure/azure-sdk-for-net/issues/7065
   - [x] Preview 2 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6917
   - [x] Preview 1 for .NET https://github.com/Azure/azure-sdk-for-net/issues/6043
