### ISSUE TITLE
Release KeyVault Track 2 Library Preview 6 for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8012]
### Features ###

- [x] API review complete and changes made as needed (#6078)
  - [x] Make all changes done to Keys and Secrets already
  - [x] Deleting Certificates should be an LRO (#8009)
  - [x] GetCertificateOperation should be removed (#8515)
  - [x] Accept multiple types of Subject Alternative Names (#8803)
  - [x] Add/rename AdministratorContacts property on CertificateIssuer (#8832)
- [x] Testing complete

### Docs ###

- [x] Make sure all public API XML doc comments are present, checked
    - [x] Improve XML doc comments for Certificates client (#8340)
- [x] Update samples
  - [x] Include more async examples, especially of async enumerables
- [x] Update READMEs
- [x] Update change log

**Comment by heaths** [comment]
Preview 6 was released.
