### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 5 for .Net

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8190]
For general summary and goals, please see: [Release Event Hub Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442).  The work items linked to this issue herein represent the tasks needed to produce the fifth preview for the "track two" Event Hubs client library.

# Design and Review
- [x] Reworking of client hierarchy and Event Processor reviewed with .NET Architect
- [x] Reworking of client hierarchy and Event Processor reviewed with Event Hubs service team
- [x] Issues created for tracking work based on the design

# Implementation

### Consuming Events
- [x] EventHubConsumer.LastEnqueuedEventInformation should return an immutable object ([#7862](https://github.com/Azure/azure-sdk-for-net/issues/7862))
- [x] Refactor event processor API for the new design ([#8285](https://github.com/Azure/azure-sdk-for-net/issues/8285))

### Infrastructure
- [x] Revise client hierarchy ([#8287](https://github.com/Azure/azure-sdk-for-net/issues/8287))
- [x] Amqp Event Hub Producer ([#7191)](https://github.com/Azure/azure-sdk-for-net/issues/7191))
- [x] Allow the `EventData` body to be retrieved as a `Stream` ([#7589](https://github.com/Azure/azure-sdk-for-net/issues/7589))
- [x] User Agent not being sent with telemetry properties ([#8017](https://github.com/Azure/azure-sdk-for-net/issues/8017))
- [x] Remove embedded track one code and dependencies ([#8221](https://github.com/Azure/azure-sdk-for-net/issues/8221))

#### Stress Testing
- [x] Create a harness to exercise send/receive over a period of time, focusing on data integrity over time rather than raw performance. ([#8194](https://github.com/Azure/azure-sdk-for-net/issues/8194))
- [x] Assist Connie in working with the service team to adapt the stress test framework for track one code to the track two API. ([#8196](https://github.com/Azure/azure-sdk-for-net/issues/8196))

# Release and Documentation
- [x] Reference documentation ([#8191](https://github.com/Azure/azure-sdk-for-net/issues/8191))
- [x] Changelog ([#8191](https://github.com/Azure/azure-sdk-for-net/issues/8191))
- [x] Samples ([#8192](https://github.com/Azure/azure-sdk-for-net/issues/8192))
- [x] Release packages to Nuget
