### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 6 for .NET

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8552]
For general summary and goals, please see: [Release Event Hubs Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library.

# Design and Review
- [x] Final API review with the architecture board ([#747](https://github.com/Azure/azure-sdk/issues/747))
- [x] Incorporate architecture board review feedback ([#8583](https://github.com/Azure/azure-sdk-for-net/issues/8583))

# Implementation

### Publishing Events
- [x] Remove partition affinity from Event Hub Producer Client ([#8555](https://github.com/Azure/azure-sdk-for-net/issues/8555))

### Consuming Events
- [x] Remove partition affinity from Event Hub Consumer Client ([#8565](https://github.com/Azure/azure-sdk-for-net/issues/8565))
- [x] Migrate Event Processor Client to consuming via ReadEventsFromPartition ([#7409](https://github.com/Azure/azure-sdk-for-net/issues/7409))
- [x] Refactor the Event Processor Client and associated types ([#8580](https://github.com/Azure/azure-sdk-for-net/issues/8580))
- [x] Refactor the Blobs Event Processor Store and associated types ([#8581](https://github.com/Azure/azure-sdk-for-net/issues/8581))
- [x] Implement ReadEvents on the Event Hub Consumer Client ([#8569](https://github.com/Azure/azure-sdk-for-net/issues/8569))
- [x] Remove InMemory Partition Manager for Event Processor Client ([#8286](https://github.com/Azure/azure-sdk-for-net/issues/8286))

### Infrastructure
- [x] Implement ReadLastEnqueuedEventInformation on the Partition Context ([#8570](https://github.com/Azure/azure-sdk-for-net/issues/8570))
- [x] Implement the Partition Receiver ([#8566](https://github.com/Azure/azure-sdk-for-net/issues/8566))

#### Stress Testing
- [x] Collaborate with the Event Hubs service team to integrate the track two client with nightly stress runs ([#8574](https://github.com/Azure/azure-sdk-for-net/issues/8574))
- [x] Setup the local stress client and perform periodic prolonged runs ([#8573](https://github.com/Azure/azure-sdk-for-net/issues/8573))

# Release and Documentation
- [x] Reference documentation ([#8553](https://github.com/Azure/azure-sdk-for-net/issues/8553))
- [x] Changelog ([#8553](https://github.com/Azure/azure-sdk-for-net/issues/8553))
- [x] Samples ([#8554](https://github.com/Azure/azure-sdk-for-net/issues/8554))
- [x] Release packages to Nuget

 🏃
