### ISSUE TITLE
Release KeyVault Track 2 Library Preview 7 for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#8675]
### Features ###

- [x] Testing complete
  - [x] Performance and reliability testing complete

### Bug fixes ###

- [x] Require resources in challenge-based authentication to use HTTPS (#9355)

### Docs ###

- [x] Update READMEs
- [x] Update change log
