### ISSUE TITLE
Event Hubs Client Library for .NET - January Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#9040]
For general summary and goals, please see: [Release Event Hubs Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Review the final API skeleton with the .NET feature team and architect; determine potential areas for tuning
- [x] Create issues and perform resource planning for the next milestone

# Implementation

### Stress and Stability

- [x] Stress and Stability Testing ([#9044](https://github.com/Azure/azure-sdk-for-net/issues/9044))
- [x] Update Service Stress Client for new API ([#9046](https://github.com/Azure/azure-sdk-for-net/issues/9046))
- [x] Test Stabilization ([#9047](https://github.com/Azure/azure-sdk-for-net/issues/9047))
- [x] Fix potential null dereference in the `AmqpMessageConverter` ([#9052](https://github.com/Azure/azure-sdk-for-net/issues/9052))
- [x] Exception when resuming processing from a checkpoint ([#9213](https://github.com/Azure/azure-sdk-for-net/issues/9213))

### Diagnostics

- [x] Integrate logging into the Event Processor Client and associated types ([#8571](https://github.com/Azure/azure-sdk-for-net/issues/8571))
- [x] Integrate logging into the Blobs Event Processor Store types ([#8663](https://github.com/Azure/azure-sdk-for-net/issues/8663))

### Configuration 

- [x] Review project file configuration and overrides ([#9050](https://github.com/Azure/azure-sdk-for-net/issues/9050))

# Release and Documentation
- [x] Create a Migration Guide ([#9065](https://github.com/Azure/azure-sdk-for-net/issues/9065))
- [x] Reference documentation ([#9041](https://github.com/Azure/azure-sdk-for-net/issues/9041))
- [x] Changelog ([#9041](https://github.com/Azure/azure-sdk-for-net/issues/9041))
- [x] Samples ([#9042](https://github.com/Azure/azure-sdk-for-net/issues/9042))
- [x] Update Azure SDK repository change log
- [x] Release Event Hubs core package to Nuget
- [x] Restore package reference to Event Hubs core from Event Hubs processor after package is released
- [x] Release Event Hubs Processor package to Nuget
