### ISSUE TITLE
Create an Amazing Dev-time Credential Experience for Azure.Identity

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#9309]
Tracking issue for feature work specific to Developer-time Azure.Identity Credential Experience

- [ ] Bring back file based auth for Management Plane: https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet#mgmt-auth AZURE_AUTH_LOCATION (see https://github.com/Azure/azure-sdk-for-net/pull/9312) (@ellismg driving design requirements)

- [ ] Add Support for writing back to the SharedTokenCache (@schaabs driving design requirements)

- [ ] Add Linux and Mac SharedTokenCache Support (@jianghaolu driving design requirements)

- [ ] Improve DefaultAzureCredential/ChainedTokenCredential - e.g., tell me what Credential I'm using for dev debug scenarios (@catalinaperalta driving design requirements)

- [ ] Have ManagedIdentityCredential utilize the AZURE_CLIENT_ID environment variable. To allow user assigned identities to utilize DefaultAzureCredential (@jongio driving implementation with vendor team)

- [ ] Have TokenCredentialOptions utilize AZURE_AUTHORITY_HOST environment variable.  To allow other clouds to use DefaultAzureCredential. (@jongio driving implementation with vendor team)

- [ ] CliCredentials / Better support for dev creds: CLI, PSH, VS, VS CODE, VS ONLINE, CLOUD SHELL
   - devCredentials (@schaabs driving design requirements)
   - CliCredential (@jongio driving implementation with vendor team)

**Comment by joshfree** [comment]
Closing epic
