### ISSUE TITLE
Event Hubs Client Library for .NET - March Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#9554]
For general summary and goals, please see: [Release Event Hubs Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Review the base event processor design with the architecture board
- [x] Review the partition receiver design with the architecture board
- [x] Design and propose an approach for the IOT Hub connection string translation
- [x] Create issues and perform resource planning for the next milestone

# Implementation

### General

- [x] Review use of `await using` and ensure that it is synchronization context agnostic ([#9564](https://github.com/Azure/azure-sdk-for-net/issues/9564))
- [x] Include Event Hubs in API compatibility scans when GA packages are published ([#9579](https://github.com/Azure/azure-sdk-for-net/issues/9579))
- [x] Test in Azure Stack and document any workarounds ([#9984](https://github.com/Azure/azure-sdk-for-net/issues/9984))

### Diagnostics

- [x] Add the `AzureEventSourceListener` trait to the Event Hubs event sources ([#9559](https://github.com/Azure/azure-sdk-for-net/issues/9559))
- [x] Distributed tracing: Use short span names ([#9071](https://github.com/Azure/azure-sdk-for-net/issues/9071))
- [x] Distributed tracing: Span kinds changes ([#9092](https://github.com/Azure/azure-sdk-for-net/issues/9092))
- [x] Distributed tracing: Add links on Send ([#9073](https://github.com/Azure/azure-sdk-for-net/issues/9073))
- [x] Distributed tracing: Stamp EventHubs info on processing spans ([#9075](https://github.com/Azure/azure-sdk-for-net/issues/9075))
- [x] Distributed Tracing: Move message spans outside of Send spans ([#8760](https://github.com/Azure/azure-sdk-for-net/issues/8760))
- [x] Distributed tracing for Event Hub: do not populate schema in peer.address attribute ([#9631](https://github.com/Azure/azure-sdk-for-net/issues/9631))
- [x] Distributed tracing for EventHubs: add enqueueTime to Process span links ([#9633](https://github.com/Azure/azure-sdk-for-net/issues/9633))

### Stress and Stability

- [x] Address gaps in Event Processor test coverage ([#9227](https://github.com/Azure/azure-sdk-for-net/issues/9227))

# Release and Documentation

- [x] Rename migration guide to MigrationGuide.md ([#9841](https://github.com/Azure/azure-sdk-for-net/issues/9841))
- [x] Add note on unified tracing & auth in migration guide ([#9787](https://github.com/Azure/azure-sdk-for-net/issues/9787))
