### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 1 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#9624]
This tracks the work to release the Azure Cognitive Search Track2 Preview 1 Library for .NET

### API Design
- [x] Document operation APIs
- [x] Document upload/merge/delete APIs
- [ ] Service APIs
- [x] ArchBoard review for querying
- [x] API Review 

### Implementation / investigations
- [x] Document Operations
- [x] Document upload/merge/delete APIs
- [ ] Language agnostic testing framework investigation for HERO scenarios

### Readme and docs
- [x] Readme
- [x] Getting started doc
- [ ] Samples and snippets
