### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 2 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#9717]
This tracks the work to release the Azure Cognitive Search Track2 Preview 2 Library for .NET

### Arch board
- [ ] Review user defined schemas (part 2)
  - [x] Serialization of strongly typed objects
  - [ ] FieldBuilder (reflection driven schema definition)
- [ ] ArchBoard review for batching
- [ ] API review for Index operations

### Features
- [x] Service APIs
- [x] React to feedback from Preview 1 around document operations
- [x] Finish the Document upload/merge/delete implementation
- [x] Implement index management operations
- [x] Design proposal for 
  - [x] Skillset
  - [x] Synonyms
- [ ] Design and implement batching operation for document operations 
- [ ] ~Expose JSON serialization controls to the user~
- [ ] FacetResults strong types
- [x] Continuation tokens design
- [ ] Move spatial types to Azure.Core
- [ ] Move SearchDocument to Azure.Core

### Docs
- [ ] Schedule UX study 
  - [ ] Define hypothesis
