### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 3 for .NET

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#9718]
This tracks the work to release the Azure Cognitive Search Track2 Preview 3 Library for .NET

### Arch board
- [ ] API review for Index operations
- [ ] Field Builder
- [ ] Review user defined schemas (part 3)
- [ ] ArchBoard review for batching

### Features
- [x] Index Operations
  - [x] Finish implementation for
    - [x] Skillset (https://github.com/Azure/azure-sdk-for-net/issues/11165)
    - [x] Synonyms (https://github.com/azure/azure-sdk-for-net/issues/10725)
    - [x] Other (https://github.com/azure/azure-sdk-for-net/issues/10748, https://github.com/azure/azure-sdk-for-net/issues/11052, https://github.com/azure/azure-sdk-for-net/issues/9472, https://github.com/azure/azure-sdk-for-net/issues/11053)
  - [x] Design and implement 
    - [x] Indexers (https://github.com/Azure/azure-sdk-for-net/issues/11164)
    - [x] DataSources (https://github.com/Azure/azure-sdk-for-net/issues/11163)
- [ ] Document Operations
  - [ ] ~Design and implement batching operation for document operations  (https://github.com/Azure/azure-sdk-for-net/issues/11161, https://github.com/azure/azure-sdk-for-net/issues/10594, https://github.com/azure/azure-sdk-for-net/issues/10593)~
  - [ ] FacetResults strong types (https://github.com/azure/azure-sdk-for-net/issues/10613)
  - [ ] Move spatial types to Azure.Core (https://github.com/azure/azure-sdk-for-net/issues/10592)
  - [ ] Move SearchDocument to Azure.Core (https://github.com/azure/azure-sdk-for-net/issues/10589, https://github.com/azure/azure-sdk-for-net/issues/10591, https://github.com/azure/azure-sdk-for-net/issues/10596, https://github.com/azure/azure-sdk-for-net/issues/10601, https://github.com/azure/azure-sdk-for-net/issues/10602, https://github.com/azure/azure-sdk-for-net/issues/10606, https://github.com/azure/azure-sdk-for-net/issues/10609, https://github.com/azure/azure-sdk-for-net/issues/10944, https://github.com/azure/azure-sdk-for-net/issues/8699)
  - [ ] Other (https://github.com/azure/azure-sdk-for-net/issues/10598, https://github.com/azure/azure-sdk-for-net/issues/10600, https://github.com/azure/azure-sdk-for-net/issues/10610, https://github.com/azure/azure-sdk-for-net/issues/10612, https://github.com/azure/azure-sdk-for-net/issues/10848, https://github.com/azure/azure-sdk-for-net/issues/8719)
  - [ ] Tracking from Core (https://github.com/azure/azure-sdk-for-net/issues/10611, https://github.com/azure/azure-sdk-for-net/issues/10604)
- [ ] Cross language consistency meeting and API Review (https://github.com/Azure/azure-sdk-for-net/issues/11162)
- [ ] Address feedback from Arch Board / UX Study (https://github.com/Azure/azure-sdk-for-net/issues/11167)
- [x] Swagger (https://github.com/azure/azure-sdk-for-net/issues/10874)

### Docs
- [x] UX Study
  - [x] Schedule UX Study
  - [x] Define hypothesis
  - [x] Run UX Study
