### ISSUE TITLE
Event Hubs Client Library for .NET - April Milestone

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#9831]
For general summary and goals, please see: [Release Event Hubs Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442).  The work items linked to this issue herein represent the tasks needed to produce the .NET Event Hubs client library for the current milestone.

# Design, Review, and Planning

- [x] Follow-up on the IoT Hub connection string design
- [x] Create issues and perform resource planning for the next milestone

# Implementation

### Event Processing

- [x] Implement the Partition Receiver ([#9323](https://github.com/Azure/azure-sdk-for-net/issues/9323))
- [x] Implement the Event Processor Base ([#9324](https://github.com/Azure/azure-sdk-for-net/issues/9324))
- [x] Update the Event Processor Client to Derive From Event Processor<T> ([#10843](https://github.com/Azure/azure-sdk-for-net/issues/10843))

### General

- [x] [BUG] EH SDK: Enqueued Time on root activity, not on the links ([#10324](https://github.com/Azure/azure-sdk-for-net/issues/10324))
- [x] EventProcessorClient failing to Start when Fully Qualified Namespace is malformed; Error Handler not invoked ([#10576](https://github.com/Azure/azure-sdk-for-net/issues/10576))
- [x] Review ASP.NET Core extension methods before the next release ([#8635](https://github.com/Azure/azure-sdk-for-net/issues/8635))

# Release and Documentation

- [x] Reference documentation ([#9555](https://github.com/Azure/azure-sdk-for-net/issues/9555))
- [x] Changelog ([#9555](https://github.com/Azure/azure-sdk-for-net/issues/9555))
- [x] Samples ([#9556](https://github.com/Azure/azure-sdk-for-net/issues/9556))
