### ISSUE TITLE
March release of KeyVault for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#9832]
# Features

- [ ] Add new Soft Delete properties to Key Vault data plane (#10046)
- [ ] KeyOperations needs to support "import" for 7.1-preview (#10063)

# Bugs

- [x] SecretClient.PurgeDeletedSecret is not properly recording failures (#9658)
- [x] CertificateClientLiveTests should reset challenge cache in record and playback modes (#9356)
- [x] Importing certificates into Azure KeyVault fails due to bad base64 encoding (#9963)
- [x] MergeCertificateAsync does not serialize request body (#9986)

**Comment by heaths** [comment]
Keys and Secrets 4.0.2, Certificates 4.0.1, and preview releases for all version 4.1.0-preview.1 have shipped.
