### ISSUE TITLE
July release of Key Vault for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#9981]
# Bugs

- [x] KeyVault - SecretClient.GetSecret(string key) return Status: 401 (Unauthorized) (#9737)
- [x] JsonWebKey is not writeable (https://github.com/azure/azure-sdk-for-net/issues/12084)
- [x] The return value of issuer name always be null (#10908)
- [x] KeyResolver requires extra "get" permissions (#11574)

**Comment by heaths** [comment]
This has shipped.
